"""mtg-synergy-graph: deterministic Forge-DSL graph engine.

Implements SPEC.md v1.2.2. Phase 1 (parser + schema) and Phase 2 (graph
matchers) live here. The package is designed to be importable as an external
dependency by mtg-edh-builder; the public surface is `SynergyEngine` once
Phase 3 lands.
"""

from .parser import (
    CHAIN_KEYS,
    CONDITIONAL_BRANCH_KINDS,
    ChainNode,
    parse_card_file,
    parse_card_text,
    parse_deck_hints,
    parse_forge_line,
    walk_svar_chain,
)
from .ports import (
    extract_cost_ports,
    extract_effect_ports,
    extract_keyword_ports,
    extract_replacement_ports,
    extract_scaling_ports,
    extract_static_ports,
    extract_trigger_ports,
    extract_all_ports,
)
from .graph_engine import (
    EVENT_MATCH_MAP,
    COST_FEEDS_TRIGGER,
    REPLACEMENT_BLOCKS_TRIGGER,
    filter_matches,
    find_amplifier_matches,
    find_lord_matches,
    find_replacement_conflicts,
    find_trigger_feeders,
    load_ports_for,
    load_ports_for_set,
    match_event,
)
from .scoring import (
    BRANCH_MULTIPLIER,
    parser_branch_kinds,
    score_all_candidates,
    score_one,
)
from .graph_metrics import (
    build_causal_graph,
    card_hub_scores,
    cmdr_two_hop_ratio,
    compute_commander_metrics,
    global_pagerank,
    neighbor_overlap,
    personalised_pagerank,
)
from .graph_cache import (
    CachedCardMetrics,
    GraphCacheStats,
    build_graph_cache,
    cache_is_populated,
    clear_graph_cache,
    commander_neighbours,
    load_card_metrics,
    neighbours_of,
)
from .heuristics import (
    STAPLE_SCORE,
    STAPLES,
    STRATEGIC_RULES,
    active_rules_for_commander,
    evaluate_strategic_rules,
    staple_bonus,
)
from .penalties import HARD_FILTER_SCORE, apply_penalties
from .complement_rules import (
    COMPLEMENT_RULES,
    ComplementRule,
    PortComplement,
    find_all_complements,
)
from .universal_scorer import (
    UniversalScore,
    score_all_universal,
)
from .engine import (
    SPEC_VERSION,
    ENGINE_VERSION,
    ContributingPort,
    Recommendation,
    RecommendationPage,
    SynergyEngine,
)
from .validate import (
    EdhrecComparison,
    GoldenSetEntry,
    GoldenSetReport,
    bootstrap_golden_set,
    check_golden_set,
    commander_to_slug,
    compare_to_edhrec,
    compute_ndcg,
    edhrec_labels_for_commander,
    regression_failed,
)

__all__ = [
    "CHAIN_KEYS",
    "CONDITIONAL_BRANCH_KINDS",
    "ChainNode",
    "parse_card_file",
    "parse_card_text",
    "parse_deck_hints",
    "parse_forge_line",
    "walk_svar_chain",
    "extract_cost_ports",
    "extract_effect_ports",
    "extract_keyword_ports",
    "extract_replacement_ports",
    "extract_scaling_ports",
    "extract_static_ports",
    "extract_trigger_ports",
    "extract_all_ports",
    "EVENT_MATCH_MAP",
    "COST_FEEDS_TRIGGER",
    "REPLACEMENT_BLOCKS_TRIGGER",
    "filter_matches",
    "find_amplifier_matches",
    "find_lord_matches",
    "find_replacement_conflicts",
    "find_trigger_feeders",
    "load_ports_for",
    "load_ports_for_set",
    "match_event",
    "BRANCH_MULTIPLIER",
    "parser_branch_kinds",
    "score_all_candidates",
    "score_one",
    "build_causal_graph",
    "card_hub_scores",
    "cmdr_two_hop_ratio",
    "compute_commander_metrics",
    "global_pagerank",
    "neighbor_overlap",
    "personalised_pagerank",
    "CachedCardMetrics",
    "GraphCacheStats",
    "build_graph_cache",
    "cache_is_populated",
    "clear_graph_cache",
    "commander_neighbours",
    "load_card_metrics",
    "neighbours_of",
    "STAPLE_SCORE",
    "STAPLES",
    "STRATEGIC_RULES",
    "active_rules_for_commander",
    "evaluate_strategic_rules",
    "staple_bonus",
    "HARD_FILTER_SCORE",
    "apply_penalties",
    "COMPLEMENT_RULES",
    "ComplementRule",
    "PortComplement",
    "find_all_complements",
    "UniversalScore",
    "score_all_universal",
    "SPEC_VERSION",
    "ENGINE_VERSION",
    "ContributingPort",
    "Recommendation",
    "RecommendationPage",
    "SynergyEngine",
    "EdhrecComparison",
    "GoldenSetEntry",
    "GoldenSetReport",
    "bootstrap_golden_set",
    "check_golden_set",
    "commander_to_slug",
    "compare_to_edhrec",
    "compute_ndcg",
    "edhrec_labels_for_commander",
    "regression_failed",
]
