"""Scaffold a new complement rule from a gap_report.py proposal.

End-to-end automation of the rule-writing step. Reads the top
proposal from the auditor (or accepts an explicit signature), looks
up the matching template in the generator catalog, and emits:

  - ``src/mtg_synergy_graph/complement_rules/generated/<rule_id>.py``
    A self-contained module with the helper function AND the gate
    predicate. Importable + callable as-is.
  - ``tests/test_generated_<rule_id>.py``
    Test class with gate rejection, per-tier match, dedup, and
    rule_id assertions.
  - stdout: integration patches (which lines to add to core.py /
    registry.py / universal_scorer.py).

With ``--apply``, the patches are automatically written to the
target files. Without ``--apply`` (default), the patches are
printed for manual review.

Generators in the catalog map 1:1 to templates in
``scripts/gap_report.py``. Adding a new template = adding a new
generator function here.
"""

from __future__ import annotations

import argparse
import re
import sqlite3
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

# Ensure we can import gap_report for the proposal types.
sys.path.insert(0, str(Path(__file__).parent))
from gap_report import (
    GapStat,
    RuleProposal,
    _commander_names,
    _propose,
    _scan_universe,
)

REPO_ROOT = Path(__file__).parent.parent
GENERATED_DIR = REPO_ROOT / "src" / "mtg_synergy_graph" / "complement_rules" / "generated"
TESTS_DIR = REPO_ROOT / "tests"
CORE_PATH = REPO_ROOT / "src" / "mtg_synergy_graph" / "complement_rules" / "core.py"
REGISTRY_PATH = REPO_ROOT / "src" / "mtg_synergy_graph" / "complement_rules" / "registry.py"
SCORER_PATH = REPO_ROOT / "src" / "mtg_synergy_graph" / "universal_scorer.py"


@dataclass(frozen=True)
class ScaffoldArtifacts:
    """Everything needed to ship a new rule."""

    rule_id: str
    helper_module_path: Path
    helper_module_src: str
    test_module_path: Path
    test_module_src: str
    core_import_line: str
    core_dispatch_line: str
    registry_import_line: str
    registry_gate_line: str
    scorer_bucket_entry: str
    scorer_multiplier_entry: str
    bucket: str
    multiplier: float


# ---------------------------------------------------------------------------
# Template generators
# ---------------------------------------------------------------------------


def _gen_creature_count_scaler(proposal: RuleProposal) -> ScaffoldArtifacts:
    rule_id = "creature_count_scaler"
    # The helper_src below is a TEMPLATE STRING written to a generated
    # Python module — SQL inside is code-as-data, not an executed query.
    # Ruff's S608 doesn't apply; suppress at the assignment site.
    # ruff: noqa: S608  (helper_src is a code-generation template; SQL inside is data, not executed)
    helper_src = '''"""AUTO-GENERATED rule: creature_count_scaler.

Generated by scripts/scaffold_rule.py from template
'creature_count_scaler'. Hand-review before merging — fill in the
mechanical hypothesis and tune the multiplier based on validation.

Auditor context at generation time:
- Reach: {reach} commanders
- Currently uncovered: {uncovered}
- Gate: scales_with.Valid with 'Creature' in valid_filter, no other
  type token. Hamza / Shanna / Beastmaster Ascension shape.
- Tier 1 wide_anthem pool: {pool_anthem} cards
- Tier 2 token_producer pool: {pool_token} cards
"""

from __future__ import annotations

import sqlite3

from ..core import PortComplement, PortRow

#: Type tokens that disqualify a scales_with.Valid port from the
#: creature-count axis (those go to the scaling rule instead).
_OTHER_TYPE_TOKENS: frozenset[str] = frozenset(
    {{"Aura", "Equipment", "Enchantment", "Artifact", "Land", "Instant", "Sorcery", "Planeswalker"}}
)

#: Qualifier tokens whose presence routes the port into a more
#: specific sub-cell (Adeline's `attacking`, Marchesa's
#: `counters_GE`, Selvala's `wasUntappedThisTurn`, etc.). Mirrors
#: gap_report._NOTABLE_QUALIFIERS — staying in sync with the auditor's
#: sub-cell discriminators is the rule's correctness invariant.
_QUALIFIER_BLOCKERS: tuple[str, ...] = (
    "attacking", "blocking", "tapped", "untapped", "modified",
    "kicked", "counters_GE", "wasUntapped", "wasCast", "wasDealt",
)


def _creature_count_scaler_gate(port: PortRow) -> bool:
    """True iff ``port`` is a pure creature-count scales_with port.

    Pure = main token Creature, no other type token (Aura / Equipment /
    ...), AND no notable qualifier (attacking / tapped / counters_GE
    / etc.) that would route the port to a different sub-cell.
    """
    if (port.get("port_type") or "").strip() != "scales_with":
        return False
    if (port.get("event_class") or "").strip() != "Valid":
        return False
    vf = port.get("valid_filter") or ""
    if "Creature" not in vf:
        return False
    if any(tok in vf for tok in _OTHER_TYPE_TOKENS):
        return False
    return not any(tok in vf for tok in _QUALIFIER_BLOCKERS)


def _find_creature_count_scaler(
    conn: sqlite3.Connection,
    cmdr_ports: list[PortRow],
    cmdr_set: set[str],
) -> list[PortComplement]:
    """Surface go-wide payoffs for commanders that scale with creature count.

    TODO: refine the mechanical hypothesis after running validation
    against a few exemplar commanders.
    """
    if not any(_creature_count_scaler_gate(p) for p in cmdr_ports):
        return []

    # Tier 1: anthems on Creature.YouCtrl with AddPower / AddToughness /
    # AddKeyword. Highest priority — narrow pool, direct payoff.
    anthem_set: set[str] = {{
        row["card_name"]
        for row in conn.execute(
            "SELECT DISTINCT card_name FROM card_ports "
            "WHERE port_type = 'static' AND event_class = 'Continuous' "
            "AND raw_line LIKE '%Creature.YouCtrl%' "
            "AND (raw_line LIKE '%AddPower%' OR raw_line LIKE '%AddToughness%' OR raw_line LIKE '%AddKeyword%')"
        )
    }}

    # Tier 2: token producers (creature tokens via TokenScript).
    token_set: set[str] = {{
        row["card_name"]
        for row in conn.execute(
            "SELECT DISTINCT cp.card_name FROM card_ports cp "
            "JOIN cards c ON c.name = cp.card_name "
            "WHERE cp.port_type = 'effect' AND cp.event_class = 'Token' "
            "AND cp.raw_line LIKE '%TokenScript%' "
            "AND c.legal_commander = 1"
        )
    }}

    # Tier 3: other creature-count scalers (stack IDF — these are
    # cards that themselves count creatures, like Beastmaster
    # Ascension).
    scaler_set: set[str] = {{
        row["card_name"]
        for row in conn.execute(
            "SELECT DISTINCT card_name FROM card_ports "
            "WHERE port_type = 'scales_with' AND event_class = 'Valid' "
            "AND valid_filter LIKE '%Creature%'"
        )
    }}

    tier_priority = (
        ("creature_count_anthem", anthem_set),
        ("creature_count_token", token_set),
        ("creature_count_scaler_stack", scaler_set),
    )
    seen: set[str] = set()
    results: list[PortComplement] = []
    for cand_event, candidates in tier_priority:
        for name in candidates:
            if name in cmdr_set or name in seen:
                continue
            seen.add(name)
            results.append(
                PortComplement(
                    rule_id="creature_count_scaler",
                    direction="synergy",
                    candidate=name,
                    cmdr_event="creature_count",
                    cand_event=cand_event,
                )
            )
    return results
'''.format(
        reach=proposal.gap.commanders,
        uncovered=proposal.gap.commanders - proposal.gap.activations,
        pool_anthem=proposal.pool_sizes.get("wide_anthem", "?"),
        pool_token=proposal.pool_sizes.get("token_producer", "?"),
    )

    test_src = '''"""AUTO-GENERATED tests for rule: creature_count_scaler."""

from __future__ import annotations

import sqlite3

import pytest

from mtg_synergy_graph.complement_rules.generated.creature_count_scaler import (
    _creature_count_scaler_gate,
    _find_creature_count_scaler,
)

SCHEMA = """\\
CREATE TABLE cards (
    name TEXT PRIMARY KEY,
    types TEXT,
    legal_commander INTEGER DEFAULT 1
);
CREATE TABLE card_ports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    card_name TEXT NOT NULL,
    port_type TEXT NOT NULL,
    event_class TEXT NOT NULL,
    valid_filter TEXT,
    raw_line TEXT,
    counter_type TEXT,
    zone_origin TEXT,
    zone_destination TEXT,
    replacement_event TEXT,
    replacement_result TEXT
);
"""


@pytest.fixture()
def conn():
    c = sqlite3.connect(":memory:")
    c.row_factory = sqlite3.Row
    c.executescript(SCHEMA)
    yield c
    c.close()


def _add_card(conn, name, types="Creature"):
    conn.execute("INSERT OR IGNORE INTO cards (name, types) VALUES (?, ?)", (name, types))


def _add_port(conn, card_name, **kwargs):
    _add_card(conn, card_name)
    cols = ["card_name"] + list(kwargs.keys())
    vals = [card_name] + list(kwargs.values())
    placeholders = ",".join("?" * len(cols))
    conn.execute(f"INSERT INTO card_ports ({','.join(cols)}) VALUES ({placeholders})", vals)


def _port(**kwargs):
    return dict(kwargs)


class TestCreatureCountScalerGate:
    def test_non_scales_with_skips(self):
        assert not _creature_count_scaler_gate(_port(port_type="trigger", event_class="Attacks"))

    def test_non_valid_event_skips(self):
        assert not _creature_count_scaler_gate(_port(port_type="scales_with", event_class="xPaid"))

    def test_no_creature_token_skips(self):
        p = _port(port_type="scales_with", event_class="Valid", valid_filter="Land.YouCtrl")
        assert not _creature_count_scaler_gate(p)

    def test_other_type_token_skips(self):
        # scales_with.Valid with Aura -> handled by scaling rule, not this one
        p = _port(port_type="scales_with", event_class="Valid", valid_filter="Aura.YouCtrl")
        assert not _creature_count_scaler_gate(p)

    def test_creature_only_matches(self):
        p = _port(port_type="scales_with", event_class="Valid", valid_filter="Creature.YouCtrl")
        assert _creature_count_scaler_gate(p)


class TestFindCreatureCountScaler:
    def _hamza_ports(self):
        return [_port(port_type="scales_with", event_class="Valid", valid_filter="Creature.YouCtrl+counters_GE1_P1P1")]

    def test_no_matching_port_returns_empty(self, conn):
        ports = [_port(port_type="trigger", event_class="DamageDone")]
        assert _find_creature_count_scaler(conn, ports, set()) == []

    def test_anthem_tier(self, conn):
        _add_port(
            conn,
            "Coat of Arms",
            port_type="static",
            event_class="Continuous",
            raw_line="{'Mode': 'Continuous', 'Affected': 'Creature.YouCtrl', 'AddKeyword': 'Anthem'}",
        )
        results = _find_creature_count_scaler(conn, self._hamza_ports(), set())
        events = {r.candidate: r.cand_event for r in results}
        assert events.get("Coat of Arms") == "creature_count_anthem"

    def test_token_tier(self, conn):
        _add_card(conn, "Avenger of Zendikar")
        conn.execute(
            "INSERT INTO card_ports (card_name, port_type, event_class, raw_line) VALUES (?, ?, ?, ?)",
            ("Avenger of Zendikar", "effect", "Token", "{'TokenScript': 'g_0_1_plant'}"),
        )
        results = _find_creature_count_scaler(conn, self._hamza_ports(), set())
        events = {r.candidate: r.cand_event for r in results}
        assert events.get("Avenger of Zendikar") == "creature_count_token"

    def test_scaler_stack_tier(self, conn):
        _add_port(
            conn,
            "Beastmaster Ascension",
            port_type="scales_with",
            event_class="Valid",
            valid_filter="Creature.YouCtrl",
        )
        results = _find_creature_count_scaler(conn, self._hamza_ports(), set())
        events = {r.candidate: r.cand_event for r in results}
        assert events.get("Beastmaster Ascension") == "creature_count_scaler_stack"

    def test_excludes_commander(self, conn):
        _add_port(
            conn,
            "Hamza, Guardian of Arashin",
            port_type="static",
            event_class="Continuous",
            raw_line="{'Affected': 'Creature.YouCtrl', 'AddPower': '1'}",
        )
        results = _find_creature_count_scaler(
            conn, self._hamza_ports(), {"Hamza, Guardian of Arashin"}
        )
        names = {r.candidate for r in results}
        assert "Hamza, Guardian of Arashin" not in names

    def test_dedup_anthem_wins(self, conn):
        # A card matching multiple tiers gets ONE complement in the
        # highest-priority tier (anthem > token > scaler_stack).
        _add_port(
            conn,
            "Dual Card",
            port_type="static",
            event_class="Continuous",
            raw_line="{'Affected': 'Creature.YouCtrl', 'AddPower': '1'}",
        )
        conn.execute(
            "INSERT INTO card_ports (card_name, port_type, event_class, valid_filter) "
            "VALUES (?, 'scales_with', 'Valid', 'Creature.YouCtrl')",
            ("Dual Card",),
        )
        results = _find_creature_count_scaler(conn, self._hamza_ports(), set())
        dual = [r for r in results if r.candidate == "Dual Card"]
        assert len(dual) == 1
        assert dual[0].cand_event == "creature_count_anthem"

    def test_rule_id(self, conn):
        _add_port(
            conn,
            "Coat of Arms",
            port_type="static",
            event_class="Continuous",
            raw_line="{'Affected': 'Creature.YouCtrl', 'AddKeyword': 'Anthem'}",
        )
        results = _find_creature_count_scaler(conn, self._hamza_ports(), set())
        assert all(r.rule_id == "creature_count_scaler" for r in results)
'''

    return ScaffoldArtifacts(
        rule_id=rule_id,
        helper_module_path=GENERATED_DIR / f"{rule_id}.py",
        helper_module_src=helper_src,
        test_module_path=TESTS_DIR / f"test_generated_{rule_id}.py",
        test_module_src=test_src,
        core_import_line=f"from .generated.{rule_id} import _find_{rule_id}",
        core_dispatch_line=f"        out.extend(_find_{rule_id}(conn, cmdr_ports, cmdr_set))",
        registry_import_line=f"from .generated.{rule_id} import _{rule_id}_gate",
        registry_gate_line=f'    RuleGate("{rule_id}", _{rule_id}_gate),',
        scorer_bucket_entry=f'    "{rule_id}": "scaling",',
        scorer_multiplier_entry=f'    # AUTO-GENERATED — tune after validation\n    "{rule_id}": 2.0,',
        bucket="scaling",
        multiplier=2.0,
    )


_GENERATORS: dict[str, Callable[[RuleProposal], ScaffoldArtifacts]] = {
    "creature_count_scaler": _gen_creature_count_scaler,
}


# ---------------------------------------------------------------------------
# Apply: write files + patch integration points
# ---------------------------------------------------------------------------


def _ensure_generated_init() -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    init = GENERATED_DIR / "__init__.py"
    if not init.exists():
        init.write_text(
            '"""Auto-generated complement rules.\n\nProduced by `scripts/scaffold_rule.py` from auditor proposals.\n"""\n'
        )


def _patch_core(art: ScaffoldArtifacts) -> bool:
    """Insert the import + dispatch line into core.py. Idempotent."""
    src = CORE_PATH.read_text()
    if art.core_import_line in src:
        return False

    # Insert import as its own line right after the existing `from .utility
    # import (...)` block. Using re.DOTALL so the lazy ``[\s\S]+?`` actually
    # matches across newlines.
    util_import_block = re.search(r"from \.utility import \([\s\S]+?\)\n", src)
    if util_import_block is None:
        return False
    block = util_import_block.group(0)
    src = src.replace(block, block + art.core_import_line + "\n", 1)

    # Insert dispatch line into _card_attr_complements after the last
    # registered helper call (use damage_doubler_synergy as the anchor —
    # it's the most recently added port-level rule before the new ones).
    anchor = "        out.extend(_find_damage_doubler_synergy(conn, cmdr_ports, cmdr_set))"
    src = src.replace(anchor, anchor + "\n" + art.core_dispatch_line, 1)
    CORE_PATH.write_text(src)
    return True


def _patch_registry(art: ScaffoldArtifacts) -> bool:
    src = REGISTRY_PATH.read_text()
    if art.registry_import_line in src:
        return False

    # Insert import after the existing `from .core import` block.
    src = src.replace(
        "from .core import COMPLEMENT_RULES, PortRow",
        f"from .core import COMPLEMENT_RULES, PortRow\n{art.registry_import_line}",
        1,
    )
    # Insert RuleGate entry at the END of _CARD_ATTR_GATES tuple.
    src = src.replace(
        '    RuleGate("aura_equipment_support", _aura_equipment_support_gate),\n)',
        f'    RuleGate("aura_equipment_support", _aura_equipment_support_gate),\n{art.registry_gate_line}\n)',
        1,
    )
    REGISTRY_PATH.write_text(src)
    return True


def _patch_scorer(art: ScaffoldArtifacts) -> bool:
    src = SCORER_PATH.read_text()
    if f'"{art.rule_id}":' in src:
        return False

    # Insert bucket entry into _RULE_TO_BUCKET.
    src = src.replace(
        '    "peer_evasion_tribal": "port_match",\n}',
        f'    "peer_evasion_tribal": "port_match",\n{art.scorer_bucket_entry}\n}}',
        1,
    )
    # Insert multiplier entry — append to end of _RULE_QUALITY_MULTIPLIER.
    src = src.replace(
        '    "peer_evasion_tribal": 2.0,\n}',
        f'    "peer_evasion_tribal": 2.0,\n{art.scorer_multiplier_entry}\n}}',
        1,
    )
    SCORER_PATH.write_text(src)
    return True


def apply_artifacts(art: ScaffoldArtifacts) -> dict[str, bool]:
    _ensure_generated_init()
    art.helper_module_path.write_text(art.helper_module_src)
    art.test_module_path.write_text(art.test_module_src)
    return {
        "helper_module": True,
        "test_module": True,
        "core_patched": _patch_core(art),
        "registry_patched": _patch_registry(art),
        "scorer_patched": _patch_scorer(art),
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _pick_top_proposal(conn: sqlite3.Connection) -> RuleProposal | None:
    commanders = _commander_names(conn)
    stats = _scan_universe(conn, commanders)
    eligible = [s for s in stats if s.activation_rate < 1.0]
    eligible.sort(key=lambda s: (-s.impact, -s.commanders, s.signature))
    for gap in eligible:
        prop = _propose(gap, conn)
        if prop is not None and prop.template in _GENERATORS:
            return prop
    return None


def _print_integration_steps(art: ScaffoldArtifacts) -> None:
    print(f"\n=== Integration plan for `{art.rule_id}` ===")
    print("\nGenerated files:")
    print(f"  {art.helper_module_path.relative_to(REPO_ROOT)}")
    print(f"  {art.test_module_path.relative_to(REPO_ROOT)}")
    print("\ncomplement_rules/core.py:")
    print(f"  + {art.core_import_line}")
    print(f"  + {art.core_dispatch_line.lstrip()}")
    print("\ncomplement_rules/registry.py:")
    print(f"  + {art.registry_import_line}")
    print(f"  + (in _CARD_ATTR_GATES tuple) {art.registry_gate_line.lstrip()}")
    print("\nuniversal_scorer.py:")
    print(f"  + (in _RULE_TO_BUCKET) {art.scorer_bucket_entry.lstrip()}")
    print(f"  + (in _RULE_QUALITY_MULTIPLIER) {art.scorer_multiplier_entry.splitlines()[-1].lstrip()}")
    print("\nValidate:")
    print(f"  uv run pytest {art.test_module_path.relative_to(REPO_ROOT)} -v")
    print("  uv run python scripts/golden_set_track.py --baseline tests/fixtures/golden_set_run.json")
    print("  uv run python scripts/gap_report.py  # confirm cell drops out of queue")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", type=Path, default=Path("data/synergy.db"))
    parser.add_argument("--template", help="explicit template to scaffold (default: top auditor proposal)")
    parser.add_argument("--apply", action="store_true", help="write files AND patch integration points")
    args = parser.parse_args()

    conn = sqlite3.connect(args.db)
    conn.row_factory = sqlite3.Row
    try:
        if args.template:
            if args.template not in _GENERATORS:
                print(f"error: no generator for template '{args.template}'", file=sys.stderr)
                print(f"available: {sorted(_GENERATORS)}", file=sys.stderr)
                return 2
            # Build a synthetic proposal from a stub gap. The user
            # would pass a real signature in a more complete CLI; for
            # now templating uses default reach=0.
            stub = GapStat(signature=("", "", ""), commanders=0, activations=0, exemplars=(), top_rules=())
            stub_proposal = RuleProposal(
                gap=stub,
                template=args.template,
                rationale="",
                gate_sketch="",
                tier_sketches=(),
                pool_sizes={},
            )
            art = _GENERATORS[args.template](stub_proposal)
        else:
            proposal = _pick_top_proposal(conn)
            if proposal is None:
                print("No proposal in the queue matches a registered generator.", file=sys.stderr)
                print(f"Available generators: {sorted(_GENERATORS)}", file=sys.stderr)
                return 1
            print(
                f"Top proposal: `{proposal.gap.signature[0]}.{proposal.gap.signature[1]}[{proposal.gap.signature[2] or '*'}]` "
                f"(reach={proposal.gap.commanders}, template={proposal.template})",
                file=sys.stderr,
            )
            art = _GENERATORS[proposal.template](proposal)
    finally:
        conn.close()

    if args.apply:
        results = apply_artifacts(art)
        print(f"\nApplied artifacts for `{art.rule_id}`:", file=sys.stderr)
        for k, v in results.items():
            status = "wrote" if v else "skipped (already present)"
            print(f"  {k}: {status}", file=sys.stderr)
        print("\nNow run:", file=sys.stderr)
        print(f"  uv run pytest {art.test_module_path.relative_to(REPO_ROOT)} -v", file=sys.stderr)
        print(
            "  uv run python scripts/golden_set_track.py --baseline tests/fixtures/golden_set_run.json", file=sys.stderr
        )
        print("  uv run python scripts/gap_report.py  # cell should drop", file=sys.stderr)
    else:
        _print_integration_steps(art)
        print("\n(Re-run with --apply to write files + patch integration points)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
