"""Scaffold a new complement rule from a gap_report.py proposal.

End-to-end automation of the rule-writing step. Reads the top
proposal from the auditor (or accepts an explicit signature), looks
up the matching template in the generator catalog, and emits:

  - ``src/mtg_synergy_graph/complement_rules/generated/<rule_id>.py``
    A self-contained module with the helper function AND the gate
    predicate. Importable + callable as-is.
  - ``tests/test_generated_<rule_id>.py``
    Test class with gate rejection, per-tier match, dedup, and
    rule_id assertions.
  - stdout: integration patches (which lines to add to core.py /
    registry.py / universal_scorer.py).

With ``--apply``, the patches are automatically written to the
target files. Without ``--apply`` (default), the patches are
printed for manual review.

Generators in the catalog map 1:1 to templates in
``scripts/gap_report.py``. Adding a new template = adding a new
generator function here.
"""

from __future__ import annotations

import argparse
import importlib
import json
import re
import shutil
import sqlite3
import subprocess
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

# Ensure we can import gap_report for the proposal types.
sys.path.insert(0, str(Path(__file__).parent))
from _attempt_log import (
    AttemptRecord,
    is_known_bad,
    is_template_blocked,
    now_iso,
    record_attempt,
    template_pass_rate,
    template_stats,
)
from gap_report import (
    GapStat,
    RuleProposal,
    _commander_names,
    _propose,
    _scan_universe,
)

REPO_ROOT = Path(__file__).parent.parent
GENERATED_DIR = REPO_ROOT / "src" / "mtg_synergy_graph" / "complement_rules" / "generated"
TESTS_DIR = REPO_ROOT / "tests"
CORE_PATH = REPO_ROOT / "src" / "mtg_synergy_graph" / "complement_rules" / "core.py"
REGISTRY_PATH = REPO_ROOT / "src" / "mtg_synergy_graph" / "complement_rules" / "registry.py"
SCORER_PATH = REPO_ROOT / "src" / "mtg_synergy_graph" / "universal_scorer.py"


@dataclass(frozen=True)
class ScaffoldArtifacts:
    """Everything needed to ship a new rule."""

    rule_id: str
    helper_module_path: Path
    helper_module_src: str
    test_module_path: Path
    test_module_src: str
    core_import_line: str
    core_dispatch_line: str
    registry_import_line: str
    registry_gate_line: str
    scorer_bucket_entry: str
    scorer_multiplier_entry: str
    bucket: str
    multiplier: float


# ---------------------------------------------------------------------------
# Template generators
# ---------------------------------------------------------------------------


def _gen_creature_count_scaler(proposal: RuleProposal) -> ScaffoldArtifacts:
    rule_id = "creature_count_scaler"
    # The helper_src below is a TEMPLATE STRING written to a generated
    # Python module — SQL inside is code-as-data, not an executed query.
    # Ruff's S608 doesn't apply; suppress at the assignment site.
    # ruff: noqa: S608  (helper_src is a code-generation template; SQL inside is data, not executed)
    helper_src = '''"""AUTO-GENERATED rule: creature_count_scaler.

Generated by scripts/scaffold_rule.py from template
'creature_count_scaler'. Hand-review before merging — fill in the
mechanical hypothesis and tune the multiplier based on validation.

Auditor context at generation time:
- Reach: {reach} commanders
- Currently uncovered: {uncovered}
- Gate: scales_with.Valid with 'Creature' in valid_filter, no other
  type token. Hamza / Shanna / Beastmaster Ascension shape.
- Tier 1 wide_anthem pool: {pool_anthem} cards
- Tier 2 token_producer pool: {pool_token} cards
"""

from __future__ import annotations

import sqlite3

from ..core import PortComplement, PortRow

#: Type tokens that disqualify a scales_with.Valid port from the
#: creature-count axis (those go to the scaling rule instead).
_OTHER_TYPE_TOKENS: frozenset[str] = frozenset(
    {{"Aura", "Equipment", "Enchantment", "Artifact", "Land", "Instant", "Sorcery", "Planeswalker"}}
)

#: Qualifier tokens whose presence routes the port into a more
#: specific sub-cell (Adeline's `attacking`, Marchesa's
#: `counters_GE`, Selvala's `wasUntappedThisTurn`, etc.). Mirrors
#: gap_report._NOTABLE_QUALIFIERS — staying in sync with the auditor's
#: sub-cell discriminators is the rule's correctness invariant.
_QUALIFIER_BLOCKERS: tuple[str, ...] = (
    "attacking", "blocking", "tapped", "untapped", "modified",
    "kicked", "counters_GE", "wasUntapped", "wasCast", "wasDealt",
)


def _creature_count_scaler_gate(port: PortRow) -> bool:
    """True iff ``port`` is a pure creature-count scales_with port.

    Pure = main token Creature, no other type token (Aura / Equipment /
    ...), AND no notable qualifier (attacking / tapped / counters_GE
    / etc.) that would route the port to a different sub-cell.
    """
    if (port.get("port_type") or "").strip() != "scales_with":
        return False
    if (port.get("event_class") or "").strip() != "Valid":
        return False
    vf = port.get("valid_filter") or ""
    if "Creature" not in vf:
        return False
    if any(tok in vf for tok in _OTHER_TYPE_TOKENS):
        return False
    return not any(tok in vf for tok in _QUALIFIER_BLOCKERS)


def _find_creature_count_scaler(
    conn: sqlite3.Connection,
    cmdr_ports: list[PortRow],
    cmdr_set: set[str],
) -> list[PortComplement]:
    """Surface go-wide payoffs for commanders that scale with creature count.

    TODO: refine the mechanical hypothesis after running validation
    against a few exemplar commanders.
    """
    if not any(_creature_count_scaler_gate(p) for p in cmdr_ports):
        return []

    # Tier 1: anthems on Creature.YouCtrl with AddPower / AddToughness /
    # AddKeyword. Highest priority — narrow pool, direct payoff.
    anthem_set: set[str] = {{
        row["card_name"]
        for row in conn.execute(
            "SELECT DISTINCT card_name FROM card_ports "
            "WHERE port_type = 'static' AND event_class = 'Continuous' "
            "AND raw_line LIKE '%Creature.YouCtrl%' "
            "AND (raw_line LIKE '%AddPower%' OR raw_line LIKE '%AddToughness%' OR raw_line LIKE '%AddKeyword%')"
        )
    }}

    # Tier 2: token producers (creature tokens via TokenScript).
    token_set: set[str] = {{
        row["card_name"]
        for row in conn.execute(
            "SELECT DISTINCT cp.card_name FROM card_ports cp "
            "JOIN cards c ON c.name = cp.card_name "
            "WHERE cp.port_type = 'effect' AND cp.event_class = 'Token' "
            "AND cp.raw_line LIKE '%TokenScript%' "
            "AND c.legal_commander = 1"
        )
    }}

    # Tier 3: other creature-count scalers (stack IDF — these are
    # cards that themselves count creatures, like Beastmaster
    # Ascension).
    scaler_set: set[str] = {{
        row["card_name"]
        for row in conn.execute(
            "SELECT DISTINCT card_name FROM card_ports "
            "WHERE port_type = 'scales_with' AND event_class = 'Valid' "
            "AND valid_filter LIKE '%Creature%'"
        )
    }}

    tier_priority = (
        ("creature_count_anthem", anthem_set),
        ("creature_count_token", token_set),
        ("creature_count_scaler_stack", scaler_set),
    )
    seen: set[str] = set()
    results: list[PortComplement] = []
    for cand_event, candidates in tier_priority:
        for name in candidates:
            if name in cmdr_set or name in seen:
                continue
            seen.add(name)
            results.append(
                PortComplement(
                    rule_id="creature_count_scaler",
                    direction="synergy",
                    candidate=name,
                    cmdr_event="creature_count",
                    cand_event=cand_event,
                )
            )
    return results
'''.format(
        reach=proposal.gap.commanders,
        uncovered=proposal.gap.commanders - proposal.gap.activations,
        pool_anthem=proposal.pool_sizes.get("wide_anthem", "?"),
        pool_token=proposal.pool_sizes.get("token_producer", "?"),
    )

    test_src = '''"""AUTO-GENERATED tests for rule: creature_count_scaler."""

from __future__ import annotations

import sqlite3

import pytest

from mtg_synergy_graph.complement_rules.generated.creature_count_scaler import (
    _creature_count_scaler_gate,
    _find_creature_count_scaler,
)

SCHEMA = """\\
CREATE TABLE cards (
    name TEXT PRIMARY KEY,
    types TEXT,
    legal_commander INTEGER DEFAULT 1
);
CREATE TABLE card_ports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    card_name TEXT NOT NULL,
    port_type TEXT NOT NULL,
    event_class TEXT NOT NULL,
    valid_filter TEXT,
    raw_line TEXT,
    counter_type TEXT,
    zone_origin TEXT,
    zone_destination TEXT,
    replacement_event TEXT,
    replacement_result TEXT
);
"""


@pytest.fixture()
def conn():
    c = sqlite3.connect(":memory:")
    c.row_factory = sqlite3.Row
    c.executescript(SCHEMA)
    yield c
    c.close()


def _add_card(conn, name, types="Creature"):
    conn.execute("INSERT OR IGNORE INTO cards (name, types) VALUES (?, ?)", (name, types))


def _add_port(conn, card_name, **kwargs):
    _add_card(conn, card_name)
    cols = ["card_name"] + list(kwargs.keys())
    vals = [card_name] + list(kwargs.values())
    placeholders = ",".join("?" * len(cols))
    conn.execute(f"INSERT INTO card_ports ({','.join(cols)}) VALUES ({placeholders})", vals)


def _port(**kwargs):
    return dict(kwargs)


class TestCreatureCountScalerGate:
    def test_non_scales_with_skips(self):
        assert not _creature_count_scaler_gate(_port(port_type="trigger", event_class="Attacks"))

    def test_non_valid_event_skips(self):
        assert not _creature_count_scaler_gate(_port(port_type="scales_with", event_class="xPaid"))

    def test_no_creature_token_skips(self):
        p = _port(port_type="scales_with", event_class="Valid", valid_filter="Land.YouCtrl")
        assert not _creature_count_scaler_gate(p)

    def test_other_type_token_skips(self):
        # scales_with.Valid with Aura -> handled by scaling rule, not this one
        p = _port(port_type="scales_with", event_class="Valid", valid_filter="Aura.YouCtrl")
        assert not _creature_count_scaler_gate(p)

    def test_creature_only_matches(self):
        p = _port(port_type="scales_with", event_class="Valid", valid_filter="Creature.YouCtrl")
        assert _creature_count_scaler_gate(p)


class TestFindCreatureCountScaler:
    def _shanna_ports(self):
        # Pure creature-count scales_with port (no counter / attacking /
        # tapped qualifier). Shanna, Sisay's Legacy is the canonical
        # exemplar — gate rejects qualifier-bearing variants.
        return [_port(port_type="scales_with", event_class="Valid", valid_filter="Creature.YouCtrl")]

    def test_no_matching_port_returns_empty(self, conn):
        ports = [_port(port_type="trigger", event_class="DamageDone")]
        assert _find_creature_count_scaler(conn, ports, set()) == []

    def test_anthem_tier(self, conn):
        _add_port(
            conn,
            "Coat of Arms",
            port_type="static",
            event_class="Continuous",
            raw_line="{'Mode': 'Continuous', 'Affected': 'Creature.YouCtrl', 'AddKeyword': 'Anthem'}",
        )
        results = _find_creature_count_scaler(conn, self._shanna_ports(), set())
        events = {r.candidate: r.cand_event for r in results}
        assert events.get("Coat of Arms") == "creature_count_anthem"

    def test_token_tier(self, conn):
        _add_card(conn, "Avenger of Zendikar")
        conn.execute(
            "INSERT INTO card_ports (card_name, port_type, event_class, raw_line) VALUES (?, ?, ?, ?)",
            ("Avenger of Zendikar", "effect", "Token", "{'TokenScript': 'g_0_1_plant'}"),
        )
        results = _find_creature_count_scaler(conn, self._shanna_ports(), set())
        events = {r.candidate: r.cand_event for r in results}
        assert events.get("Avenger of Zendikar") == "creature_count_token"

    def test_scaler_stack_tier(self, conn):
        _add_port(
            conn,
            "Beastmaster Ascension",
            port_type="scales_with",
            event_class="Valid",
            valid_filter="Creature.YouCtrl",
        )
        results = _find_creature_count_scaler(conn, self._shanna_ports(), set())
        events = {r.candidate: r.cand_event for r in results}
        assert events.get("Beastmaster Ascension") == "creature_count_scaler_stack"

    def test_excludes_commander(self, conn):
        _add_port(
            conn,
            "Shanna, Sisay's Legacy",
            port_type="static",
            event_class="Continuous",
            raw_line="{'Affected': 'Creature.YouCtrl', 'AddPower': '1'}",
        )
        results = _find_creature_count_scaler(
            conn, self._shanna_ports(), {"Shanna, Sisay's Legacy"}
        )
        names = {r.candidate for r in results}
        assert "Shanna, Sisay's Legacy" not in names

    def test_qualifier_blocker_rejects_gate(self):
        # counters_GE / attacking / tapped route to other rules; the
        # bare-cell rule must not fire on them.
        p = _port(port_type="scales_with", event_class="Valid", valid_filter="Creature.YouCtrl+counters_GE1_P1P1")
        assert not _creature_count_scaler_gate(p)

    def test_dedup_anthem_wins(self, conn):
        # A card matching multiple tiers gets ONE complement in the
        # highest-priority tier (anthem > token > scaler_stack).
        _add_port(
            conn,
            "Dual Card",
            port_type="static",
            event_class="Continuous",
            raw_line="{'Affected': 'Creature.YouCtrl', 'AddPower': '1'}",
        )
        conn.execute(
            "INSERT INTO card_ports (card_name, port_type, event_class, valid_filter) "
            "VALUES (?, 'scales_with', 'Valid', 'Creature.YouCtrl')",
            ("Dual Card",),
        )
        results = _find_creature_count_scaler(conn, self._shanna_ports(), set())
        dual = [r for r in results if r.candidate == "Dual Card"]
        assert len(dual) == 1
        assert dual[0].cand_event == "creature_count_anthem"

    def test_rule_id(self, conn):
        _add_port(
            conn,
            "Coat of Arms",
            port_type="static",
            event_class="Continuous",
            raw_line="{'Affected': 'Creature.YouCtrl', 'AddKeyword': 'Anthem'}",
        )
        results = _find_creature_count_scaler(conn, self._shanna_ports(), set())
        assert all(r.rule_id == "creature_count_scaler" for r in results)
'''

    return ScaffoldArtifacts(
        rule_id=rule_id,
        helper_module_path=GENERATED_DIR / f"{rule_id}.py",
        helper_module_src=helper_src,
        test_module_path=TESTS_DIR / f"test_generated_{rule_id}.py",
        test_module_src=test_src,
        core_import_line=f"from .generated.{rule_id} import _find_{rule_id}  # noqa: E402",
        core_dispatch_line=f"        out.extend(_find_{rule_id}(conn, cmdr_ports, cmdr_set))",
        registry_import_line=f"from .generated.{rule_id} import _{rule_id}_gate",
        registry_gate_line=f'    RuleGate("{rule_id}", _{rule_id}_gate),',
        scorer_bucket_entry=f'    "{rule_id}": "scaling",',
        scorer_multiplier_entry=f'    # AUTO-GENERATED — tune after validation\n    "{rule_id}": 2.0,',
        bucket="scaling",
        multiplier=2.0,
    )


_KEYWORD_SANITIZE_RE = re.compile(r"[^a-z0-9]+")


def _sanitize_for_identifier(name: str) -> str:
    """Coerce a keyword (e.g. ``Doctor's``, ``Ward:2``) into a Python
    identifier-safe slug (``doctors``, ``ward_2``).
    """
    s = _KEYWORD_SANITIZE_RE.sub("_", name.lower()).strip("_")
    return s or "unknown"


def _gen_peer_tribal_keyword(proposal: RuleProposal) -> ScaffoldArtifacts:
    """Generate a small-pool keyword-tribal rule.

    Reads the keyword name from ``proposal.gap.signature[1]`` (the
    event_class). Each keyword scaffolds its own module + rule_id —
    simpler to revert than maintaining a shared frozenset, and the
    auditor handles each keyword as an independent gap.
    """
    keyword = proposal.gap.signature[1]
    if not keyword:
        raise ValueError("peer_tribal_keyword needs a non-empty keyword")
    slug = _sanitize_for_identifier(keyword)
    rule_id = f"{slug}_tribal"
    pool_size = proposal.pool_sizes.get("same_keyword", "?")

    helper_src = f'''"""AUTO-GENERATED rule: {rule_id}.

Generated by scripts/scaffold_rule.py from template
'peer_tribal_keyword' on the keyword '{keyword}'. Surfaces the
small-pool of cards sharing this keyword as natural archetype
partners.

Auditor context at generation time:
- Reach: {proposal.gap.commanders} commanders carrying keyword.{keyword}
- Currently uncovered: {proposal.gap.commanders - proposal.gap.activations}
- Pool: {pool_size} cards with this keyword
"""

from __future__ import annotations

import sqlite3

from ..core import PortComplement, PortRow

#: The keyword this rule fires on. Single-keyword scope by design —
#: each new keyword scaffolds its own module so reverts stay isolated.
_KEYWORD = {keyword!r}


def _{rule_id}_gate(port: PortRow) -> bool:
    """True iff ``port`` is a keyword port for the target keyword."""
    if (port.get("port_type") or "").strip() != "keyword":
        return False
    return (port.get("event_class") or "").strip() == _KEYWORD


def _find_{rule_id}(
    conn: sqlite3.Connection,
    cmdr_ports: list[PortRow],
    cmdr_set: set[str],
) -> list[PortComplement]:
    """Return every other card carrying the same keyword.

    Pool is small by gate construction (auditor only proposes this
    template for keywords with <=100 cards), so IDF naturally rewards
    these matches without needing a hand-tuned multiplier.
    """
    if not any(_{rule_id}_gate(p) for p in cmdr_ports):
        return []

    rows = conn.execute(
        "SELECT DISTINCT card_name FROM card_ports "
        "WHERE port_type = 'keyword' AND event_class = ?",
        (_KEYWORD,),
    )
    results: list[PortComplement] = []
    for row in rows:
        name = row["card_name"]
        if name in cmdr_set:
            continue
        results.append(
            PortComplement(
                rule_id={rule_id!r},
                direction="synergy",
                candidate=name,
                cmdr_event={rule_id!r},
                cand_event="same_keyword_partner",
            )
        )
    return results
'''

    test_src = f'''"""AUTO-GENERATED tests for rule: {rule_id}."""

from __future__ import annotations

import sqlite3

import pytest

from mtg_synergy_graph.complement_rules.generated.{rule_id} import (
    _find_{rule_id},
    _{rule_id}_gate,
)

SCHEMA = """\\
CREATE TABLE cards (name TEXT PRIMARY KEY, types TEXT);
CREATE TABLE card_ports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    card_name TEXT NOT NULL,
    port_type TEXT NOT NULL,
    event_class TEXT NOT NULL,
    valid_filter TEXT,
    raw_line TEXT,
    counter_type TEXT,
    zone_origin TEXT,
    zone_destination TEXT,
    replacement_event TEXT,
    replacement_result TEXT
);
"""


@pytest.fixture()
def conn():
    c = sqlite3.connect(":memory:")
    c.row_factory = sqlite3.Row
    c.executescript(SCHEMA)
    yield c
    c.close()


def _add_keyword(conn, name, keyword):
    conn.execute("INSERT OR IGNORE INTO cards (name) VALUES (?)", (name,))
    conn.execute(
        "INSERT INTO card_ports (card_name, port_type, event_class) VALUES (?, 'keyword', ?)",
        (name, keyword),
    )


def _port(**kwargs):
    return dict(kwargs)


class Test{slug.title().replace("_", "")}Gate:
    def test_non_keyword_port_skips(self):
        assert not _{rule_id}_gate(_port(port_type="trigger", event_class={keyword!r}))

    def test_other_keyword_skips(self):
        assert not _{rule_id}_gate(_port(port_type="keyword", event_class="Flying"))

    def test_target_keyword_matches(self):
        assert _{rule_id}_gate(_port(port_type="keyword", event_class={keyword!r}))


class TestFind{slug.title().replace("_", "")}:
    def _cmdr_ports(self):
        return [_port(port_type="keyword", event_class={keyword!r})]

    def test_no_keyword_port_returns_empty(self, conn):
        assert _find_{rule_id}(conn, [_port(port_type="trigger", event_class="Attacks")], set()) == []

    def test_finds_other_cards_with_keyword(self, conn):
        _add_keyword(conn, "Partner Card A", {keyword!r})
        _add_keyword(conn, "Partner Card B", {keyword!r})
        results = _find_{rule_id}(conn, self._cmdr_ports(), set())
        names = {{r.candidate for r in results}}
        assert "Partner Card A" in names
        assert "Partner Card B" in names

    def test_excludes_other_keyword_cards(self, conn):
        _add_keyword(conn, "Wrong Keyword Card", "Flying")
        results = _find_{rule_id}(conn, self._cmdr_ports(), set())
        names = {{r.candidate for r in results}}
        assert "Wrong Keyword Card" not in names

    def test_excludes_commander(self, conn):
        _add_keyword(conn, "Self Commander", {keyword!r})
        results = _find_{rule_id}(conn, self._cmdr_ports(), {{"Self Commander"}})
        names = {{r.candidate for r in results}}
        assert "Self Commander" not in names

    def test_rule_id(self, conn):
        _add_keyword(conn, "Partner Card", {keyword!r})
        results = _find_{rule_id}(conn, self._cmdr_ports(), set())
        assert all(r.rule_id == {rule_id!r} for r in results)
        assert all(r.cand_event == "same_keyword_partner" for r in results)
'''

    return ScaffoldArtifacts(
        rule_id=rule_id,
        helper_module_path=GENERATED_DIR / f"{rule_id}.py",
        helper_module_src=helper_src,
        test_module_path=TESTS_DIR / f"test_generated_{rule_id}.py",
        test_module_src=test_src,
        core_import_line=f"from .generated.{rule_id} import _find_{rule_id}  # noqa: E402",
        core_dispatch_line=f"        out.extend(_find_{rule_id}(conn, cmdr_ports, cmdr_set))",
        registry_import_line=f"from .generated.{rule_id} import _{rule_id}_gate",
        registry_gate_line=f'    RuleGate("{rule_id}", _{rule_id}_gate),',
        scorer_bucket_entry=f'    "{rule_id}": "port_match",',
        scorer_multiplier_entry=f'    # AUTO-GENERATED keyword-tribal — IDF handles weighting\n    "{rule_id}": 2.0,',
        bucket="port_match",
        multiplier=2.0,
    )


def _gen_replacement_stack(proposal: RuleProposal) -> ScaffoldArtifacts:
    """Generator for the replacement_stack template.

    A commander with ``replacement.<event>[<result>]`` (e.g. Anafenza's
    "creatures dying go to exile instead") wants other cards with the
    SAME (event, result) shape — they stack the same replacement effect.
    Same shape as peer_tribal_keyword but keyed on
    ``(event_class, replacement_result)`` instead of a keyword.
    """
    event = proposal.gap.signature[1]
    result = proposal.gap.signature[2]
    if not event or not result:
        raise ValueError("replacement_stack needs non-empty event_class and replacement_result")
    slug = f"repl_{_sanitize_for_identifier(event)}_{_sanitize_for_identifier(result)}_stack"
    rule_id = slug
    pool_size = proposal.pool_sizes.get("same_shape", "?")

    helper_src = f'''"""AUTO-GENERATED rule: {rule_id}.

Generated by scripts/scaffold_rule.py from template
'replacement_stack' on the (event, result) pair
({event!r}, {result!r}). Surfaces the small pool of cards sharing
the same replacement event + result as natural archetype partners.

Auditor context at generation time:
- Reach: {proposal.gap.commanders} commanders carrying replacement.{event}[{result}]
- Currently uncovered: {proposal.gap.commanders - proposal.gap.activations}
- Pool: {pool_size} cards with this replacement shape
"""

from __future__ import annotations

import sqlite3

from ..core import PortComplement, PortRow

#: The (event, result) pair this rule fires on. Single-shape scope by
#: design — each new pair scaffolds its own module so reverts stay
#: isolated.
_EVENT = {event!r}
_RESULT = {result!r}


def _{rule_id}_gate(port: PortRow) -> bool:
    """True iff ``port`` is a replacement port for the target shape."""
    if (port.get("port_type") or "").strip() != "replacement":
        return False
    if (port.get("event_class") or "").strip() != _EVENT:
        return False
    return (port.get("replacement_result") or "").strip() == _RESULT


def _find_{rule_id}(
    conn: sqlite3.Connection,
    cmdr_ports: list[PortRow],
    cmdr_set: set[str],
) -> list[PortComplement]:
    """Return every other card carrying the same replacement shape.

    Pool is small by gate construction (auditor only proposes this
    template for shapes with limited card pools), so IDF naturally
    rewards these matches.
    """
    if not any(_{rule_id}_gate(p) for p in cmdr_ports):
        return []

    rows = conn.execute(
        "SELECT DISTINCT card_name FROM card_ports "
        "WHERE port_type = 'replacement' "
        "AND event_class = ? AND replacement_result = ?",
        (_EVENT, _RESULT),
    )
    results: list[PortComplement] = []
    for row in rows:
        name = row["card_name"]
        if name in cmdr_set:
            continue
        results.append(
            PortComplement(
                rule_id={rule_id!r},
                direction="synergy",
                candidate=name,
                cmdr_event={rule_id!r},
                cand_event="same_shape_replacement",
            )
        )
    return results
'''

    test_src = f'''"""AUTO-GENERATED tests for rule: {rule_id}."""

from __future__ import annotations

import sqlite3

import pytest

from mtg_synergy_graph.complement_rules.generated.{rule_id} import (
    _find_{rule_id},
    _{rule_id}_gate,
)

SCHEMA = """\\
CREATE TABLE cards (name TEXT PRIMARY KEY, types TEXT);
CREATE TABLE card_ports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    card_name TEXT NOT NULL,
    port_type TEXT NOT NULL,
    event_class TEXT NOT NULL,
    valid_filter TEXT,
    raw_line TEXT,
    counter_type TEXT,
    zone_origin TEXT,
    zone_destination TEXT,
    replacement_event TEXT,
    replacement_result TEXT
);
"""


@pytest.fixture()
def conn():
    c = sqlite3.connect(":memory:")
    c.row_factory = sqlite3.Row
    c.executescript(SCHEMA)
    yield c
    c.close()


def _add_repl(conn, name, event, result):
    conn.execute("INSERT OR IGNORE INTO cards (name) VALUES (?)", (name,))
    conn.execute(
        "INSERT INTO card_ports (card_name, port_type, event_class, replacement_result) "
        "VALUES (?, 'replacement', ?, ?)",
        (name, event, result),
    )


def _port(**kwargs):
    return dict(kwargs)


class TestGate:
    def test_non_replacement_skips(self):
        assert not _{rule_id}_gate(_port(port_type="trigger", event_class={event!r}, replacement_result={result!r}))

    def test_other_event_skips(self):
        assert not _{rule_id}_gate(_port(port_type="replacement", event_class="OtherEvent", replacement_result={result!r}))

    def test_other_result_skips(self):
        assert not _{rule_id}_gate(_port(port_type="replacement", event_class={event!r}, replacement_result="OtherResult"))

    def test_target_shape_matches(self):
        assert _{rule_id}_gate(_port(port_type="replacement", event_class={event!r}, replacement_result={result!r}))


class TestFind:
    def _cmdr_ports(self):
        return [_port(port_type="replacement", event_class={event!r}, replacement_result={result!r})]

    def test_no_replacement_port_returns_empty(self, conn):
        assert _find_{rule_id}(conn, [_port(port_type="trigger", event_class="Attacks")], set()) == []

    def test_finds_other_cards_with_same_shape(self, conn):
        _add_repl(conn, "Partner Card A", {event!r}, {result!r})
        _add_repl(conn, "Partner Card B", {event!r}, {result!r})
        results = _find_{rule_id}(conn, self._cmdr_ports(), set())
        names = {{r.candidate for r in results}}
        assert "Partner Card A" in names
        assert "Partner Card B" in names

    def test_excludes_other_shapes(self, conn):
        _add_repl(conn, "Wrong Result Card", {event!r}, "OtherResult")
        _add_repl(conn, "Wrong Event Card", "OtherEvent", {result!r})
        results = _find_{rule_id}(conn, self._cmdr_ports(), set())
        names = {{r.candidate for r in results}}
        assert "Wrong Result Card" not in names
        assert "Wrong Event Card" not in names

    def test_excludes_commander(self, conn):
        _add_repl(conn, "Self Commander", {event!r}, {result!r})
        results = _find_{rule_id}(conn, self._cmdr_ports(), {{"Self Commander"}})
        names = {{r.candidate for r in results}}
        assert "Self Commander" not in names

    def test_rule_id(self, conn):
        _add_repl(conn, "Partner Card", {event!r}, {result!r})
        results = _find_{rule_id}(conn, self._cmdr_ports(), set())
        assert all(r.rule_id == {rule_id!r} for r in results)
        assert all(r.cand_event == "same_shape_replacement" for r in results)
'''

    return ScaffoldArtifacts(
        rule_id=rule_id,
        helper_module_path=GENERATED_DIR / f"{rule_id}.py",
        helper_module_src=helper_src,
        test_module_path=TESTS_DIR / f"test_generated_{rule_id}.py",
        test_module_src=test_src,
        core_import_line=f"from .generated.{rule_id} import _find_{rule_id}  # noqa: E402",
        core_dispatch_line=f"        out.extend(_find_{rule_id}(conn, cmdr_ports, cmdr_set))",
        registry_import_line=f"from .generated.{rule_id} import _{rule_id}_gate",
        registry_gate_line=f'    RuleGate("{rule_id}", _{rule_id}_gate),',
        scorer_bucket_entry=f'    "{rule_id}": "port_match",',
        scorer_multiplier_entry=f'    # AUTO-GENERATED replacement-stack — IDF handles weighting\n    "{rule_id}": 2.0,',
        bucket="port_match",
        multiplier=2.0,
    )


def _gen_x_cost_scaler(proposal: RuleProposal) -> ScaffoldArtifacts:
    """Generator for the x_cost_scaler template.

    Commanders that scales_with.xPaid (Walking Ballista, Comet Storm,
    Hangarback Walker, the Hydras, Mistform Ultimus) want more mana to
    pay X. Two narrow tiers — mana doublers (~11 cards) and other
    scales_with.xPaid cards (~94). Skips ritual / generic-mana tiers
    because they're broad enough to risk regressing other commanders.
    """
    rule_id = "x_cost_scaler"
    pool_doubler = proposal.pool_sizes.get("mana_doubler", "?")

    helper_src = f'''"""AUTO-GENERATED rule: {rule_id}.

Generated by scripts/scaffold_rule.py from template
'x_cost_scaler'. Surfaces mana doublers and other X-cost cards for
commanders whose abilities scale with X paid.

Auditor context at generation time:
- Reach: {proposal.gap.commanders} commanders carrying scales_with.xPaid
- Currently uncovered: {proposal.gap.commanders - proposal.gap.activations}
- Tier 1 mana_doubler pool: {pool_doubler} cards (replacement.ProduceMana)
"""

from __future__ import annotations

import sqlite3

from ..core import PortComplement, PortRow


def _{rule_id}_gate(port: PortRow) -> bool:
    """True iff ``port`` is a scales_with.xPaid port."""
    if (port.get("port_type") or "").strip() != "scales_with":
        return False
    return (port.get("event_class") or "").strip() == "xPaid"


def _find_{rule_id}(
    conn: sqlite3.Connection,
    cmdr_ports: list[PortRow],
    cmdr_set: set[str],
) -> list[PortComplement]:
    """Surface mana doublers and other X-cost stackers."""
    if not any(_{rule_id}_gate(p) for p in cmdr_ports):
        return []

    # Tier 1: mana doublers (replacement effects on ProduceMana).
    # Tiny pool (~11) — high IDF reward.
    doubler_set: set[str] = {{
        row["card_name"]
        for row in conn.execute(
            "SELECT DISTINCT card_name FROM card_ports "
            "WHERE port_type = 'replacement' AND replacement_event = 'ProduceMana'"
        )
    }}

    # Tier 2: other X-cost cards. Same archetype, stack IDF.
    stacker_set: set[str] = {{
        row["card_name"]
        for row in conn.execute(
            "SELECT DISTINCT card_name FROM card_ports "
            "WHERE port_type = 'scales_with' AND event_class = 'xPaid'"
        )
    }}

    tier_priority = (
        ("x_cost_mana_doubler", doubler_set),
        ("x_cost_stacker", stacker_set),
    )
    seen: set[str] = set()
    results: list[PortComplement] = []
    for cand_event, candidates in tier_priority:
        for name in candidates:
            if name in cmdr_set or name in seen:
                continue
            seen.add(name)
            results.append(
                PortComplement(
                    rule_id={rule_id!r},
                    direction="synergy",
                    candidate=name,
                    cmdr_event="x_cost",
                    cand_event=cand_event,
                )
            )
    return results
'''

    test_src = f'''"""AUTO-GENERATED tests for rule: {rule_id}."""

from __future__ import annotations

import sqlite3

import pytest

from mtg_synergy_graph.complement_rules.generated.{rule_id} import (
    _find_{rule_id},
    _{rule_id}_gate,
)

SCHEMA = """\\
CREATE TABLE cards (name TEXT PRIMARY KEY, types TEXT);
CREATE TABLE card_ports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    card_name TEXT NOT NULL,
    port_type TEXT NOT NULL,
    event_class TEXT NOT NULL,
    valid_filter TEXT,
    raw_line TEXT,
    counter_type TEXT,
    zone_origin TEXT,
    zone_destination TEXT,
    replacement_event TEXT,
    replacement_result TEXT
);
"""


@pytest.fixture()
def conn():
    c = sqlite3.connect(":memory:")
    c.row_factory = sqlite3.Row
    c.executescript(SCHEMA)
    yield c
    c.close()


def _add_card(conn, name):
    conn.execute("INSERT OR IGNORE INTO cards (name) VALUES (?)", (name,))


def _port(**kwargs):
    return dict(kwargs)


class TestXCostScalerGate:
    def test_non_scales_with_skips(self):
        assert not _{rule_id}_gate(_port(port_type="trigger", event_class="xPaid"))

    def test_other_event_skips(self):
        assert not _{rule_id}_gate(_port(port_type="scales_with", event_class="Valid"))

    def test_xpaid_matches(self):
        assert _{rule_id}_gate(_port(port_type="scales_with", event_class="xPaid"))


class TestFindXCostScaler:
    def _cmdr_ports(self):
        return [_port(port_type="scales_with", event_class="xPaid")]

    def test_no_xpaid_port_returns_empty(self, conn):
        assert _find_{rule_id}(conn, [_port(port_type="trigger", event_class="Attacks")], set()) == []

    def test_doubler_tier(self, conn):
        _add_card(conn, "Mana Reflection")
        conn.execute(
            "INSERT INTO card_ports (card_name, port_type, event_class, replacement_event) "
            "VALUES (?, 'replacement', 'TapsForMana', 'ProduceMana')",
            ("Mana Reflection",),
        )
        results = _find_{rule_id}(conn, self._cmdr_ports(), set())
        events = {{r.candidate: r.cand_event for r in results}}
        assert events.get("Mana Reflection") == "x_cost_mana_doubler"

    def test_stacker_tier(self, conn):
        _add_card(conn, "Walking Ballista")
        conn.execute(
            "INSERT INTO card_ports (card_name, port_type, event_class) "
            "VALUES (?, 'scales_with', 'xPaid')",
            ("Walking Ballista",),
        )
        results = _find_{rule_id}(conn, self._cmdr_ports(), set())
        events = {{r.candidate: r.cand_event for r in results}}
        assert events.get("Walking Ballista") == "x_cost_stacker"

    def test_excludes_commander(self, conn):
        _add_card(conn, "Self Cmdr")
        conn.execute(
            "INSERT INTO card_ports (card_name, port_type, event_class) "
            "VALUES (?, 'scales_with', 'xPaid')",
            ("Self Cmdr",),
        )
        results = _find_{rule_id}(conn, self._cmdr_ports(), {{"Self Cmdr"}})
        names = {{r.candidate for r in results}}
        assert "Self Cmdr" not in names

    def test_dedup_doubler_wins(self, conn):
        _add_card(conn, "Dual")
        conn.execute(
            "INSERT INTO card_ports (card_name, port_type, event_class, replacement_event) "
            "VALUES (?, 'replacement', 'TapsForMana', 'ProduceMana')",
            ("Dual",),
        )
        conn.execute(
            "INSERT INTO card_ports (card_name, port_type, event_class) "
            "VALUES (?, 'scales_with', 'xPaid')",
            ("Dual",),
        )
        results = _find_{rule_id}(conn, self._cmdr_ports(), set())
        dual = [r for r in results if r.candidate == "Dual"]
        assert len(dual) == 1
        assert dual[0].cand_event == "x_cost_mana_doubler"

    def test_rule_id(self, conn):
        _add_card(conn, "Mana Doubler")
        conn.execute(
            "INSERT INTO card_ports (card_name, port_type, event_class, replacement_event) "
            "VALUES (?, 'replacement', 'TapsForMana', 'ProduceMana')",
            ("Mana Doubler",),
        )
        results = _find_{rule_id}(conn, self._cmdr_ports(), set())
        assert all(r.rule_id == {rule_id!r} for r in results)
'''

    return ScaffoldArtifacts(
        rule_id=rule_id,
        helper_module_path=GENERATED_DIR / f"{rule_id}.py",
        helper_module_src=helper_src,
        test_module_path=TESTS_DIR / f"test_generated_{rule_id}.py",
        test_module_src=test_src,
        core_import_line=f"from .generated.{rule_id} import _find_{rule_id}  # noqa: E402",
        core_dispatch_line=f"        out.extend(_find_{rule_id}(conn, cmdr_ports, cmdr_set))",
        registry_import_line=f"from .generated.{rule_id} import _{rule_id}_gate",
        registry_gate_line=f'    RuleGate("{rule_id}", _{rule_id}_gate),',
        scorer_bucket_entry=f'    "{rule_id}": "scaling",',
        scorer_multiplier_entry=f'    # AUTO-GENERATED x-cost scaler — IDF handles weighting\n    "{rule_id}": 2.0,',
        bucket="scaling",
        multiplier=2.0,
    )


def _gen_counter_removal_payoff(proposal: RuleProposal) -> ScaffoldArtifacts:
    """Generator for the counter_removal_payoff template.

    Commanders that remove +1/+1 counters as an activation cost
    (Ghave, Vish Kal, Karlov, Slogurk, Ulasht — counter consumers
    rather than producers). They want a steady stream of P1P1
    counters feeding their abilities.

    Two tiers in priority order:
      1. doubler (~16 cards): replacement.AddCounter P1P1 — narrowest
         pool, highest IDF (Hardened Scales / Doubling Season class).
      2. proliferate (~82 cards): effect.Proliferate — adds to existing.

    Producer tier (effect.PutCounter[All] P1P1, ~1700 cards) was tried
    first and reverted — touching that broad pool with a third rule
    perturbed the multi-rule bonus enough to drop golden NDCG by
    0.0003. Counter producers are already surfaced for affected
    commanders by counter_axis_feeder + modified_axis_feeder; this
    rule focuses on the targeted-narrow tiers those rules don't cover.

    Gate restricted to P1P1 counters specifically. Rejects:
      - LOYALTY (planeswalker self-abilities, not commanders).
      - CHARGE / OIL / KI / etc (other counter axes — different rules).
      - NICKNAME / CARDNAME targets (self-removal, e.g. Skullbriar's
        own counters; not externally-fed).

    M1M1 is a related axis (Hapatra style) but keyed off different
    producers; deferred to a separate template.
    """
    rule_id = "counter_removal_payoff"
    pool_doubler = proposal.pool_sizes.get("doubler", "?")
    pool_proliferate = proposal.pool_sizes.get("proliferate", "?")

    helper_src = f'''"""AUTO-GENERATED rule: {rule_id}.

Generated by scripts/scaffold_rule.py from template
'counter_removal_payoff'. Surfaces P1P1 counter sources for
commanders that consume P1P1 counters as activation costs.

Auditor context at generation time:
- Reach: {proposal.gap.commanders} commanders carrying cost.remove_counter
- Currently uncovered: {proposal.gap.commanders - proposal.gap.activations}
- Tier 1 doubler pool: {pool_doubler} cards
- Tier 2 proliferate pool: {pool_proliferate} cards
- (producer tier dropped after broad-pool revert; counter_axis_feeder
  already covers producers for these archetypes)
"""

from __future__ import annotations

import sqlite3

from ..core import PortComplement, PortRow


def _{rule_id}_gate(port: PortRow) -> bool:
    """True iff ``port`` is a cost.remove_counter port keyed on a
    P1P1 counter from an external source (not the card's own counters).
    """
    if (port.get("port_type") or "").strip() != "cost":
        return False
    if (port.get("event_class") or "").strip() != "remove_counter":
        return False
    cs = port.get("cost_subtype") or ""
    # cost_subtype format: "<amount>/<COUNTER_TYPE>[/<filter>...]"
    parts = cs.split("/")
    if len(parts) < 2 or parts[1] != "P1P1":
        return False
    # Reject self-targeted costs (Skullbriar etc) — those are inherent.
    return not any(tok in cs for tok in ("CARDNAME", "NICKNAME"))


def _find_{rule_id}(
    conn: sqlite3.Connection,
    cmdr_ports: list[PortRow],
    cmdr_set: set[str],
) -> list[PortComplement]:
    """Surface P1P1-counter producers, doublers, and proliferate effects.

    Tier dedup: a card matching multiple tiers gets one complement in
    the highest-priority tier (doubler > proliferate > producer). This
    keeps Doubling Season from emitting three competing complements.
    """
    if not any(_{rule_id}_gate(p) for p in cmdr_ports):
        return []

    # Tier 1: P1P1 counter doublers — narrowest pool, highest specificity.
    doubler_set: set[str] = {{
        row["card_name"]
        for row in conn.execute(
            "SELECT DISTINCT card_name FROM card_ports "
            "WHERE port_type = 'replacement' AND event_class = 'AddCounter' "
            "AND raw_line LIKE '%P1P1%'"
        )
    }}

    # Tier 2: Proliferate effects — direct way to grow existing counters.
    proliferate_set: set[str] = {{
        row["card_name"]
        for row in conn.execute(
            "SELECT DISTINCT card_name FROM card_ports "
            "WHERE port_type = 'effect' AND event_class = 'Proliferate'"
        )
    }}

    tier_priority = (
        ("counter_p1p1_doubler", doubler_set),
        ("counter_p1p1_proliferate", proliferate_set),
    )
    seen: set[str] = set()
    results: list[PortComplement] = []
    for cand_event, candidates in tier_priority:
        for name in candidates:
            if name in cmdr_set or name in seen:
                continue
            seen.add(name)
            results.append(
                PortComplement(
                    rule_id={rule_id!r},
                    direction="synergy",
                    candidate=name,
                    cmdr_event="counter_removal",
                    cand_event=cand_event,
                )
            )
    return results
'''

    test_src = f'''"""AUTO-GENERATED tests for rule: {rule_id}."""

from __future__ import annotations

import sqlite3

import pytest

from mtg_synergy_graph.complement_rules.generated.{rule_id} import (
    _counter_removal_payoff_gate,
    _find_counter_removal_payoff,
)

SCHEMA = """\\
CREATE TABLE cards (
    name TEXT PRIMARY KEY,
    types TEXT,
    legal_commander INTEGER DEFAULT 1
);
CREATE TABLE card_ports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    card_name TEXT NOT NULL,
    port_type TEXT NOT NULL,
    event_class TEXT NOT NULL,
    valid_filter TEXT,
    raw_line TEXT,
    counter_type TEXT,
    cost_subtype TEXT,
    zone_origin TEXT,
    zone_destination TEXT,
    replacement_event TEXT,
    replacement_result TEXT
);
"""


@pytest.fixture()
def conn():
    c = sqlite3.connect(":memory:")
    c.row_factory = sqlite3.Row
    c.executescript(SCHEMA)
    yield c
    c.close()


def _add_card(conn, name, types="Creature"):
    conn.execute("INSERT OR IGNORE INTO cards (name, types) VALUES (?, ?)", (name, types))


def _add_port(conn, card_name, **kwargs):
    _add_card(conn, card_name)
    cols = ["card_name"] + list(kwargs.keys())
    vals = [card_name] + list(kwargs.values())
    placeholders = ",".join("?" * len(cols))
    conn.execute(f"INSERT INTO card_ports ({{','.join(cols)}}) VALUES ({{placeholders}})", vals)


def _port(**kwargs):
    return dict(kwargs)


class TestCounterRemovalPayoffGate:
    def test_non_cost_port_skips(self):
        assert not _counter_removal_payoff_gate(
            _port(port_type="effect", event_class="remove_counter", cost_subtype="1/P1P1")
        )

    def test_non_remove_counter_skips(self):
        assert not _counter_removal_payoff_gate(
            _port(port_type="cost", event_class="discard", cost_subtype="1/Card")
        )

    def test_loyalty_skips(self):
        # Planeswalker self-loyalty is inherent, not a payoff axis.
        assert not _counter_removal_payoff_gate(
            _port(port_type="cost", event_class="remove_counter", cost_subtype="2/LOYALTY")
        )

    def test_charge_skips(self):
        # CHARGE / OIL / KI etc are different counter axes.
        assert not _counter_removal_payoff_gate(
            _port(port_type="cost", event_class="remove_counter", cost_subtype="3/CHARGE")
        )

    def test_self_targeted_skips(self):
        # NICKNAME / CARDNAME = removing this card's own counters.
        assert not _counter_removal_payoff_gate(
            _port(port_type="cost", event_class="remove_counter", cost_subtype="X/P1P1/NICKNAME")
        )
        assert not _counter_removal_payoff_gate(
            _port(port_type="cost", event_class="remove_counter", cost_subtype="1/P1P1/CARDNAME")
        )

    def test_p1p1_external_matches(self):
        # Ghave-style: pay 1 P1P1 from a creature you control.
        assert _counter_removal_payoff_gate(
            _port(
                port_type="cost",
                event_class="remove_counter",
                cost_subtype="1/P1P1/Creature.YouCtrl/a creature you control",
            )
        )

    def test_x_p1p1_matches(self):
        assert _counter_removal_payoff_gate(
            _port(port_type="cost", event_class="remove_counter", cost_subtype="X/P1P1")
        )


class TestFindCounterRemovalPayoff:
    def _ghave_ports(self):
        return [
            _port(
                port_type="cost",
                event_class="remove_counter",
                cost_subtype="1/P1P1/Creature.YouCtrl/a creature you control",
            )
        ]

    def test_no_matching_port_returns_empty(self, conn):
        ports = [_port(port_type="trigger", event_class="DamageDone")]
        assert _find_counter_removal_payoff(conn, ports, set()) == []

    def test_doubler_tier(self, conn):
        _add_port(
            conn,
            "Hardened Scales",
            port_type="replacement",
            event_class="AddCounter",
            raw_line="{{'ValidCounterType': 'P1P1', 'ReplaceWith': 'AddOneMore'}}",
        )
        results = _find_counter_removal_payoff(conn, self._ghave_ports(), set())
        events = {{r.candidate: r.cand_event for r in results}}
        assert events.get("Hardened Scales") == "counter_p1p1_doubler"

    def test_proliferate_tier(self, conn):
        _add_port(
            conn,
            "Inexorable Tide",
            port_type="effect",
            event_class="Proliferate",
        )
        results = _find_counter_removal_payoff(conn, self._ghave_ports(), set())
        events = {{r.candidate: r.cand_event for r in results}}
        assert events.get("Inexorable Tide") == "counter_p1p1_proliferate"

    def test_excludes_commander(self, conn):
        _add_port(
            conn,
            "Ghave, Guru of Spores",
            port_type="replacement",
            event_class="AddCounter",
            raw_line="{{'ValidCounterType': 'P1P1'}}",
        )
        results = _find_counter_removal_payoff(
            conn, self._ghave_ports(), {{"Ghave, Guru of Spores"}}
        )
        names = {{r.candidate for r in results}}
        assert "Ghave, Guru of Spores" not in names

    def test_dedup_doubler_wins(self, conn):
        # A card matching multiple tiers gets one complement in the
        # highest-priority tier (doubler > proliferate).
        _add_port(
            conn,
            "Doubling Season",
            port_type="replacement",
            event_class="AddCounter",
            raw_line="{{'ValidCounterType': 'P1P1', 'ReplaceWith': 'Twice'}}",
        )
        # Same card also has Proliferate (hypothetical) — should not double-emit.
        conn.execute(
            "INSERT INTO card_ports (card_name, port_type, event_class) "
            "VALUES (?, 'effect', 'Proliferate')",
            ("Doubling Season",),
        )
        results = _find_counter_removal_payoff(conn, self._ghave_ports(), set())
        ds = [r for r in results if r.candidate == "Doubling Season"]
        assert len(ds) == 1
        assert ds[0].cand_event == "counter_p1p1_doubler"

    def test_rule_id(self, conn):
        _add_port(
            conn,
            "Hardened Scales",
            port_type="replacement",
            event_class="AddCounter",
            raw_line="{{'ValidCounterType': 'P1P1'}}",
        )
        results = _find_counter_removal_payoff(conn, self._ghave_ports(), set())
        assert all(r.rule_id == "counter_removal_payoff" for r in results)
        assert all(r.cmdr_event == "counter_removal" for r in results)
'''

    return ScaffoldArtifacts(
        rule_id=rule_id,
        helper_module_path=GENERATED_DIR / f"{rule_id}.py",
        helper_module_src=helper_src,
        test_module_path=TESTS_DIR / f"test_generated_{rule_id}.py",
        test_module_src=test_src,
        core_import_line=f"from .generated.{rule_id} import _find_{rule_id}  # noqa: E402",
        core_dispatch_line=f"        out.extend(_find_{rule_id}(conn, cmdr_ports, cmdr_set))",
        registry_import_line=f"from .generated.{rule_id} import _{rule_id}_gate",
        registry_gate_line=f'    RuleGate("{rule_id}", _{rule_id}_gate),',
        scorer_bucket_entry=f'    "{rule_id}": "port_match",',
        scorer_multiplier_entry=f'    # AUTO-GENERATED counter_removal_payoff — small multiplier (Ghave/Karlov in golden)\n    "{rule_id}": 1.0,',
        bucket="port_match",
        multiplier=1.0,
    )


_GENERATORS: dict[str, Callable[[RuleProposal], ScaffoldArtifacts]] = {
    "creature_count_scaler": _gen_creature_count_scaler,
    "peer_tribal_keyword": _gen_peer_tribal_keyword,
    "x_cost_scaler": _gen_x_cost_scaler,
    "counter_removal_payoff": _gen_counter_removal_payoff,
    "replacement_stack": _gen_replacement_stack,
}


# ---------------------------------------------------------------------------
# Apply: write files + patch integration points
# ---------------------------------------------------------------------------


def _ensure_generated_init() -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    init = GENERATED_DIR / "__init__.py"
    if not init.exists():
        init.write_text(
            '"""Auto-generated complement rules.\n\nProduced by `scripts/scaffold_rule.py` from auditor proposals.\n"""\n'
        )


def _patch_core(art: ScaffoldArtifacts) -> bool:
    """Insert the import + dispatch line into core.py. Idempotent."""
    src = CORE_PATH.read_text()
    if art.core_import_line in src:
        return False

    # Insert import as its own line right after the existing `from .utility
    # import (...)` block. Using re.DOTALL so the lazy ``[\s\S]+?`` actually
    # matches across newlines.
    util_import_block = re.search(r"from \.utility import \([\s\S]+?\)\n", src)
    if util_import_block is None:
        return False
    block = util_import_block.group(0)
    src = src.replace(block, block + art.core_import_line + "\n", 1)

    # Insert dispatch line into _card_attr_complements after the last
    # registered helper call (use damage_doubler_synergy as the anchor —
    # it's the most recently added port-level rule before the new ones).
    anchor = "        out.extend(_find_damage_doubler_synergy(conn, cmdr_ports, cmdr_set))"
    src = src.replace(anchor, anchor + "\n" + art.core_dispatch_line, 1)
    CORE_PATH.write_text(src)
    return True


def _insert_before_container_close(src: str, name: str, entry: str, open_char: str, close_char: str) -> str | None:
    """Insert ``entry`` as the last line of a container literal named
    ``name`` (a dict, tuple, or list). Returns the modified source, or
    ``None`` if the container can't be located.

    Walks the source brace-by-brace from the container's opening
    delimiter, tracking nesting, until the matching close is found.
    Robust against any number of pre-existing entries — anchors that
    reference a specific previous entry break after each new
    insertion, this approach doesn't.
    """
    match = re.search(rf"\b{re.escape(name)}\b[^=]*=\s*{re.escape(open_char)}", src)
    if match is None:
        return None
    depth = 0
    i = match.end() - 1  # position of the opening delimiter
    while i < len(src):
        c = src[i]
        if c == open_char:
            depth += 1
        elif c == close_char:
            depth -= 1
            if depth == 0:
                # i points at the matching close. Insert entry on its
                # own line just before the line containing the close.
                line_start = src.rfind("\n", 0, i) + 1
                return src[:line_start] + entry + "\n" + src[line_start:]
        i += 1
    return None


def _patch_registry(art: ScaffoldArtifacts) -> bool:
    src = REGISTRY_PATH.read_text()
    if art.registry_import_line in src:
        return False

    # Insert import after the existing `from .core import` block.
    src = src.replace(
        "from .core import COMPLEMENT_RULES, PortRow",
        f"from .core import COMPLEMENT_RULES, PortRow\n{art.registry_import_line}",
        1,
    )
    # Insert RuleGate entry at the END of the _CARD_ATTR_GATES tuple
    # — using the brace-walking helper so subsequent insertions don't
    # depend on a specific previous entry being the last one.
    new_src = _insert_before_container_close(src, "_CARD_ATTR_GATES", art.registry_gate_line, "(", ")")
    if new_src is None:
        return False
    REGISTRY_PATH.write_text(new_src)
    return True


def _patch_scorer(art: ScaffoldArtifacts) -> bool:
    src = SCORER_PATH.read_text()
    if f'"{art.rule_id}":' in src:
        return False

    # Same brace-walking insertion for both dicts.
    new_src = _insert_before_container_close(src, "_RULE_TO_BUCKET", art.scorer_bucket_entry, "{", "}")
    if new_src is None:
        return False
    new_src = _insert_before_container_close(new_src, "_RULE_QUALITY_MULTIPLIER", art.scorer_multiplier_entry, "{", "}")
    if new_src is None:
        return False
    SCORER_PATH.write_text(new_src)
    return True


def apply_artifacts(art: ScaffoldArtifacts) -> dict[str, bool]:
    _ensure_generated_init()
    art.helper_module_path.write_text(art.helper_module_src)
    art.test_module_path.write_text(art.test_module_src)
    return {
        "helper_module": True,
        "test_module": True,
        "core_patched": _patch_core(art),
        "registry_patched": _patch_registry(art),
        "scorer_patched": _patch_scorer(art),
    }


# ---------------------------------------------------------------------------
# State capture + auto-revert (makes --apply safe to run)
# ---------------------------------------------------------------------------


def _affected_paths(art: ScaffoldArtifacts) -> list[Path]:
    """Files touched by ``apply_artifacts`` — captured before, restored
    after if validation fails. The ``generated/`` directory is created
    on demand; restoring it means deleting if it didn't exist.
    """
    return [
        art.helper_module_path,
        art.test_module_path,
        CORE_PATH,
        REGISTRY_PATH,
        SCORER_PATH,
        GENERATED_DIR / "__init__.py",
    ]


def _capture_state(paths: list[Path]) -> dict[Path, str | None]:
    """Snapshot file contents (None for files that don't yet exist).

    The snapshot is the source of truth for ``_restore_state`` — newly
    created files become None entries which restore by deletion.
    """
    return {p: (p.read_text() if p.exists() else None) for p in paths}


def _restore_state(snapshot: dict[Path, str | None]) -> None:
    """Restore each file to its captured content (or delete if it
    didn't exist when captured). Idempotent.
    """
    for path, content in snapshot.items():
        if content is None:
            path.unlink(missing_ok=True)
        else:
            path.write_text(content)
    # If the generated/ directory is now empty (we deleted the only
    # files we created), remove it so the repo stays clean.
    if GENERATED_DIR.exists() and not any(GENERATED_DIR.iterdir()):
        shutil.rmtree(GENERATED_DIR)


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


@dataclass
class ValidationResult:
    """Outcome of post-apply validation. ``passed`` is the AND of all
    individual checks; ``summary`` is a one-paragraph narrative.

    Four orthogonal signals from the orchestrator:

    - ``trivial``: passed everything but contributes no measurable
      hi_syn improvement (zero touched OR fires-but-never-lands OR
      wins offset losses to net zero). Kept on disk but blocked
      from retry.
    - ``harmful``: pre-ship impact check found NEGATIVE net hi_syn
      delta across touched commanders — rule is displacing better
      candidates from top-30. ``passed`` is False; auto-revert.
    - ``marginal``: net positive hi_syn delta but ratio
      sum/touched < 0.1 — under one improvement per ten touched
      commanders, barely above noise. Kept on disk but blocked
      from retry on the same template (don't keep shipping rules
      that barely register).
    """

    passed: bool
    summary: str
    trivial: bool = False
    trivial_reason: str | None = None
    harmful: bool = False
    harmful_reason: str | None = None
    marginal: bool = False
    marginal_reason: str | None = None


def _run(cmd: list[str], cwd: Path) -> subprocess.CompletedProcess:
    """Run a subprocess command and capture stdout+stderr.

    Inputs are hard-coded ``["uv", "run", ...]`` invocations from this
    file — no external/untrusted input flows into ``cmd``. Suppress
    ruff's S603 here because the tainted-input model doesn't apply.
    """
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, check=False)  # noqa: S603


def _validate(art: ScaffoldArtifacts, allow_ndcg_drop: float) -> ValidationResult:
    """Delegate to ``scripts/_validate_rule.py`` — one subprocess that
    runs pytest + golden + broad + the trivial-impact check.

    Consolidates four ``uv run`` cold starts (~6s of overhead) into one,
    and surfaces the trivial-impact verdict so the caller can record
    rules that pass validation but don't actually move anything.
    """
    result = _run(
        [
            "uv",
            "run",
            "python",
            "scripts/_validate_rule.py",
            "--rule-id",
            art.rule_id,
            "--allow-ndcg-drop",
            str(allow_ndcg_drop),
        ],
        cwd=REPO_ROOT,
    )
    # The orchestrator emits exactly one JSON line on stdout (the last
    # non-blank line), preceded by pytest output and other prints.
    json_line = next(
        (ln for ln in reversed(result.stdout.splitlines()) if ln.strip().startswith("{")),
        None,
    )
    if json_line is None:
        return ValidationResult(
            passed=False,
            summary=(
                f"_validate_rule.py emitted no JSON result "
                f"(exit {result.returncode}).\n\n"
                f"stdout tail:\n{result.stdout[-1500:]}\n"
                f"stderr tail:\n{result.stderr[-500:]}"
            ),
        )
    try:
        payload = json.loads(json_line)
    except json.JSONDecodeError as exc:
        return ValidationResult(
            passed=False,
            summary=f"Could not parse _validate_rule.py output: {exc}\nLine: {json_line[:500]}",
        )
    return ValidationResult(
        passed=bool(payload.get("passed")),
        summary=str(payload.get("summary", "")),
        trivial=bool(payload.get("trivial")),
        trivial_reason=payload.get("trivial_reason"),
        harmful=bool(payload.get("harmful")),
        harmful_reason=payload.get("harmful_reason"),
        marginal=bool(payload.get("marginal")),
        marginal_reason=payload.get("marginal_reason"),
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _pick_top_proposal(conn: sqlite3.Connection) -> RuleProposal | None:
    """Walk the auditor's queue, return the first proposal that:
    - has a registered generator AND
    - is not known-bad (i.e., its (template, rule_id) wasn't previously
      reverted in the attempt log).

    The known-bad skip is what makes the autonomy loop converge: every
    failed attempt is recorded, and subsequent runs walk past it to
    the next viable candidate. Pass ``--force`` to override at the
    apply stage.
    """
    commanders = _commander_names(conn)
    stats = _scan_universe(conn, commanders)
    eligible = [s for s in stats if s.activation_rate < 1.0]
    eligible.sort(key=lambda s: (-s.impact, -s.commanders, s.signature))
    for gap in eligible:
        prop = _propose(gap, conn)
        if prop is None or prop.template not in _GENERATORS:
            continue
        # Template-level block: if past attempts on this template show
        # a pass rate at or below the threshold (with enough samples),
        # skip every proposal that uses it. Avoids burning cycles on
        # generators with systemic flaws.
        t_blocked, _ = is_template_blocked(prop.template)
        if t_blocked:
            continue
        try:
            art = _GENERATORS[prop.template](prop)
        except Exception as exc:
            print(
                f"[WARN] generator '{prop.template}' raised on signature {prop.gap.signature}: {exc!r}",
                file=sys.stderr,
            )
            continue
        blocked, _ = is_known_bad(prop.template, art.rule_id)
        if blocked:
            continue
        return prop
    return None


def _print_integration_steps(art: ScaffoldArtifacts) -> None:
    print(f"\n=== Integration plan for `{art.rule_id}` ===")
    print("\nGenerated files:")
    print(f"  {art.helper_module_path.relative_to(REPO_ROOT)}")
    print(f"  {art.test_module_path.relative_to(REPO_ROOT)}")
    print("\ncomplement_rules/core.py:")
    print(f"  + {art.core_import_line}")
    print(f"  + {art.core_dispatch_line.lstrip()}")
    print("\ncomplement_rules/registry.py:")
    print(f"  + {art.registry_import_line}")
    print(f"  + (in _CARD_ATTR_GATES tuple) {art.registry_gate_line.lstrip()}")
    print("\nuniversal_scorer.py:")
    print(f"  + (in _RULE_TO_BUCKET) {art.scorer_bucket_entry.lstrip()}")
    print(f"  + (in _RULE_QUALITY_MULTIPLIER) {art.scorer_multiplier_entry.splitlines()[-1].lstrip()}")
    print("\nValidate:")
    print(f"  uv run pytest {art.test_module_path.relative_to(REPO_ROOT)} -v")
    print("  uv run python scripts/golden_set_track.py --baseline tests/fixtures/golden_set_run.json")
    print("  uv run python scripts/gap_report.py  # confirm cell drops out of queue")


def _refresh_registry() -> None:
    """Reload the runtime registry module and propagate the fresh
    ``RULE_GATES`` tuple into gap_report's namespace.

    Required between walk iterations: gap_report.RULE_GATES is bound
    at import time, so newly-registered gates from a freshly-shipped
    rule are invisible to the picker on the next iteration without
    explicit reload. Without this, the walker re-picks the same
    signature every iteration and the patcher silently no-ops on
    re-application.
    """
    from mtg_synergy_graph.complement_rules import registry

    importlib.reload(registry)
    import gap_report

    gap_report.RULE_GATES = registry.RULE_GATES


def _attempt_one(
    art: ScaffoldArtifacts,
    template_name: str,
    signature: tuple[str, str, str],
    *,
    validate: bool,
    allow_ndcg_drop: float,
    force: bool,
) -> str:
    """Run one apply+validate cycle. Returns the outcome string
    (``"passed"``, ``"reverted"``, ``"skipped"``).

    Records the outcome to the attempt log on every code path. Also
    handles the known-bad pre-check (returns ``"skipped"`` without
    touching files).
    """
    blocked, prior_reason = is_known_bad(template_name, art.rule_id)
    if blocked and not force:
        print(
            f"\n[SKIPPED] (template={template_name}, rule_id={art.rule_id}) "
            f"was previously reverted:\n  {prior_reason[:200]}",
            file=sys.stderr,
        )
        record_attempt(
            AttemptRecord(
                timestamp=now_iso(),
                rule_id=art.rule_id,
                template=template_name,
                signature=signature,
                outcome="skipped",
                reason=f"prior revert: {prior_reason[:150]}",
            )
        )
        return "skipped"

    t_blocked, t_reason = is_template_blocked(template_name)
    if t_blocked and not force:
        print(
            f"\n[SKIPPED] template `{template_name}` is blocked: {t_reason}",
            file=sys.stderr,
        )
        record_attempt(
            AttemptRecord(
                timestamp=now_iso(),
                rule_id=art.rule_id,
                template=template_name,
                signature=signature,
                outcome="skipped",
                reason=f"template blocked: {t_reason}",
            )
        )
        return "skipped"

    snapshot = _capture_state(_affected_paths(art)) if validate else None
    results = apply_artifacts(art)
    print(f"\nApplied artifacts for `{art.rule_id}`:", file=sys.stderr)
    for k, v in results.items():
        status = "wrote" if v else "skipped (already present)"
        print(f"  {k}: {status}", file=sys.stderr)

    files_touched = tuple(str(p.relative_to(REPO_ROOT)) for p in _affected_paths(art))

    if not (validate and snapshot is not None):
        print("\n(Skipped validation — re-run pytest + golden_set_track manually)", file=sys.stderr)
        return "passed"  # No validation means we trust the user; treat as passed.

    print("\nValidating (pytest + golden NDCG + broad NDCG + impact check)...", file=sys.stderr)
    result = _validate(art, allow_ndcg_drop=allow_ndcg_drop)
    if result.passed and result.trivial:
        # Kept on disk (rule is mechanically correct, no regressions),
        # but flagged as trivial so the walk loop won't keep proposing
        # the same template/signature pair without --force.
        print(f"\n[TRIVIAL] {result.summary}", file=sys.stderr)
        print(f"  reason: {result.trivial_reason}", file=sys.stderr)
        record_attempt(
            AttemptRecord(
                timestamp=now_iso(),
                rule_id=art.rule_id,
                template=template_name,
                signature=signature,
                outcome="trivial",
                reason=(result.trivial_reason or "rule activates on no validated commander"),
                files_touched=files_touched,
            )
        )
        return "trivial"
    if result.passed and result.marginal:
        # Kept on disk (mechanically correct + net positive) but signal
        # is too weak to justify continuing on this template axis. Same
        # blocking treatment as trivial.
        print(f"\n[MARGINAL] {result.summary}", file=sys.stderr)
        print(f"  reason: {result.marginal_reason}", file=sys.stderr)
        record_attempt(
            AttemptRecord(
                timestamp=now_iso(),
                rule_id=art.rule_id,
                template=template_name,
                signature=signature,
                outcome="marginal",
                reason=(result.marginal_reason or "barely-positive impact"),
                files_touched=files_touched,
            )
        )
        return "marginal"
    if result.passed:
        print(f"\n[PASS] {result.summary}", file=sys.stderr)
        record_attempt(
            AttemptRecord(
                timestamp=now_iso(),
                rule_id=art.rule_id,
                template=template_name,
                signature=signature,
                outcome="passed",
                reason=result.summary,
                files_touched=files_touched,
            )
        )
        return "passed"

    tag = "HARMFUL" if result.harmful else "FAIL"
    print(f"\n[{tag}] {result.summary}", file=sys.stderr)
    if result.harmful_reason:
        print(f"  reason: {result.harmful_reason}", file=sys.stderr)
    _restore_state(snapshot)
    print("Reverted all changes for this attempt.", file=sys.stderr)
    reason = result.harmful_reason or result.summary
    record_attempt(
        AttemptRecord(
            timestamp=now_iso(),
            rule_id=art.rule_id,
            template=template_name,
            signature=signature,
            outcome="reverted",
            reason=(f"harmful: {reason}" if result.harmful else reason)[:600],
            files_touched=files_touched,
        )
    )
    return "reverted"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", type=Path, default=Path("data/synergy.db"))
    parser.add_argument("--template", help="explicit template to scaffold (default: top auditor proposal)")
    parser.add_argument("--apply", action="store_true", help="write files AND patch integration points")
    parser.add_argument(
        "--no-validate",
        dest="validate",
        action="store_false",
        default=True,
        help="(use with --apply) skip post-apply validation. Default: validate and auto-revert on failure.",
    )
    parser.add_argument(
        "--allow-ndcg-drop",
        type=float,
        default=0.0,
        help="(use with --apply) maximum tolerated golden NDCG drop. Default 0.0 = revert on any regression.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="(use with --apply) override the attempt-log block on a "
        "(template, rule_id) previously reverted. Use after refining "
        "the template and expecting a different outcome.",
    )
    parser.add_argument(
        "--walk",
        type=int,
        default=1,
        help="(use with --apply) drain the queue: try N proposals in a "
        "row, picking the next one after each (skipping known-bad). "
        "Default 1 = single attempt, current behavior. The picker "
        "re-scans the universe each iteration so freshly-shipped "
        "rules update the queue.",
    )
    parser.add_argument(
        "--show-template-stats",
        action="store_true",
        help="Print per-template attempt statistics from the attempt log "
        "(passed/trivial/reverted/skipped + smoothed pass rate + block "
        "status) and exit. Useful for understanding which generators "
        "are paying off and which are systematically broken.",
    )
    args = parser.parse_args()

    if args.show_template_stats:
        stats = template_stats()
        if not stats:
            print("attempt log is empty — no template statistics yet.")
            return 0
        rows = []
        for t in sorted(stats):
            counts = stats[t]
            rate, fresh = template_pass_rate(t)
            blocked, _ = is_template_blocked(t)
            rows.append(
                (
                    t,
                    counts.get("passed", 0),
                    counts.get("trivial", 0),
                    counts.get("marginal", 0),
                    counts.get("reverted", 0),
                    counts.get("skipped", 0),
                    fresh,
                    rate,
                    "BLOCKED" if blocked else "ok",
                )
            )
        print(
            f"{'template':<35} {'pass':>5} {'triv':>5} {'marg':>5} {'rev':>5} "
            f"{'skip':>5} {'fresh':>6} {'rate':>6}  status"
        )
        print("-" * 86)
        for row in rows:
            print(
                f"{row[0]:<35} {row[1]:>5} {row[2]:>5} {row[3]:>5} {row[4]:>5} "
                f"{row[5]:>5} {row[6]:>6} {row[7]:>6.2f}  {row[8]}"
            )
        return 0

    if args.walk > 1 and not args.apply:
        print("error: --walk requires --apply", file=sys.stderr)
        return 2
    if args.walk > 1 and args.template:
        print("error: --walk can't be combined with --template (walk re-picks each iteration)", file=sys.stderr)
        return 2

    conn = sqlite3.connect(args.db)
    conn.row_factory = sqlite3.Row
    try:
        # Walk mode: drain the queue. Each iteration re-picks (the
        # picker skips known-bad combos), then applies+validates.
        if args.walk > 1:
            counts = {"passed": 0, "reverted": 0, "skipped": 0, "trivial": 0, "marginal": 0}
            shipped: list[str] = []
            for i in range(1, args.walk + 1):
                print(f"\n========== Walk iteration {i}/{args.walk} ==========", file=sys.stderr)
                proposal = _pick_top_proposal(conn)
                if proposal is None:
                    print("Queue exhausted (no more eligible proposals).", file=sys.stderr)
                    break
                print(
                    f"Picked: `{proposal.gap.signature[0]}.{proposal.gap.signature[1]}[{proposal.gap.signature[2] or '*'}]` "
                    f"(reach={proposal.gap.commanders}, template={proposal.template})",
                    file=sys.stderr,
                )
                art = _GENERATORS[proposal.template](proposal)
                outcome = _attempt_one(
                    art,
                    proposal.template,
                    proposal.gap.signature,
                    validate=args.validate,
                    allow_ndcg_drop=args.allow_ndcg_drop,
                    force=args.force,
                )
                counts[outcome] += 1
                if outcome == "passed":
                    shipped.append(art.rule_id)
                # Refresh the in-process registry so the next iteration's
                # picker sees freshly-registered gates (or the absence of
                # ones that were reverted). Without this, the walker
                # re-picks the same signature every iteration.
                _refresh_registry()
            print("\n========== Walk summary ==========", file=sys.stderr)
            print(
                f"  passed:   {counts['passed']}  ({', '.join(shipped) or '—'})",
                file=sys.stderr,
            )
            print(f"  marginal: {counts['marginal']}", file=sys.stderr)
            print(f"  trivial:  {counts['trivial']}", file=sys.stderr)
            print(f"  reverted: {counts['reverted']}", file=sys.stderr)
            print(f"  skipped:  {counts['skipped']}", file=sys.stderr)
            if shipped:
                print(
                    "\nReview the working tree, then commit the shipped rules.",
                    file=sys.stderr,
                )
            return 0 if counts["passed"] > 0 else 1

        # Single-attempt mode (default).
        if args.template:
            if args.template not in _GENERATORS:
                print(f"error: no generator for template '{args.template}'", file=sys.stderr)
                print(f"available: {sorted(_GENERATORS)}", file=sys.stderr)
                return 2
            stub = GapStat(signature=("", "", ""), commanders=0, activations=0, exemplars=(), top_rules=())
            stub_proposal = RuleProposal(
                gap=stub,
                template=args.template,
                rationale="",
                gate_sketch="",
                tier_sketches=(),
                pool_sizes={},
            )
            template_name = args.template
            signature: tuple[str, str, str] = ("", "", "")
            try:
                art = _GENERATORS[args.template](stub_proposal)
            except ValueError as exc:
                # Some templates require concrete signature discriminators
                # (e.g. replacement_stack needs a non-empty event_class +
                # replacement_result). The walk picker feeds these from
                # gap_report; manual --template invocations don't.
                print(
                    f"error: template '{args.template}' rejected stub proposal: {exc}",
                    file=sys.stderr,
                )
                print(
                    "       Use --apply --walk 1 to let the auditor pick a concrete signature.",
                    file=sys.stderr,
                )
                return 2
        else:
            proposal = _pick_top_proposal(conn)
            if proposal is None:
                print("No proposal in the queue matches a registered generator.", file=sys.stderr)
                print(f"Available generators: {sorted(_GENERATORS)}", file=sys.stderr)
                return 1
            print(
                f"Top proposal: `{proposal.gap.signature[0]}.{proposal.gap.signature[1]}[{proposal.gap.signature[2] or '*'}]` "
                f"(reach={proposal.gap.commanders}, template={proposal.template})",
                file=sys.stderr,
            )
            template_name = proposal.template
            signature = proposal.gap.signature
            art = _GENERATORS[proposal.template](proposal)
    finally:
        conn.close()

    if not args.apply:
        _print_integration_steps(art)
        print("\n(Re-run with --apply to write files + patch integration points)")
        return 0

    outcome = _attempt_one(
        art,
        template_name,
        signature,
        validate=args.validate,
        allow_ndcg_drop=args.allow_ndcg_drop,
        force=args.force,
    )
    if outcome == "passed":
        print("\nKept changes. Suggested next: review the diff and commit.", file=sys.stderr)
        return 0
    if outcome == "trivial":
        print(
            "\nKept changes (no regressions), but the rule contributes no "
            "measurable hi_syn improvement on any validated commander. "
            "Either broaden the gate or rethink the template hypothesis.",
            file=sys.stderr,
        )
        return 1
    if outcome == "marginal":
        print(
            "\nKept changes (mechanically positive) but signal is barely above "
            "noise (sum_Δhi_syn / touched < 0.1). Consider tightening the "
            "gate to focus on the archetype where the rule actually helps.",
            file=sys.stderr,
        )
        return 1
    if outcome == "reverted":
        print(
            "\nRefine the template (QUALIFIER_BLOCKERS, multiplier, tier "
            "choices) in scripts/scaffold_rule.py and re-run.",
            file=sys.stderr,
        )
        return 1
    # outcome == "skipped"
    print(
        "\nRefine the template in scripts/scaffold_rule.py "
        "(_QUALIFIER_BLOCKERS, multiplier, tier choices), then re-run "
        "with --force.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
