"""Sauron, the Dark Lord — Grixis (UBR) amass/temptation/LotR tribal."""

COMMANDER = "Sauron, the Dark Lord"
EDHREC_SLUG = "sauron-the-dark-lord"
COLOR_IDENTITY = {"U", "B", "R"}

DECKLIST = [
    "Sauron, the Dark Lord",
    "Anger",
    "Arcane Denial",
    "Archfiend of Ifnir",
    "Barad-dûr",
    "Bilbo, Retired Burglar",
    "Birthday Escape",
    "Blasphemous Act",
    "Book of Mazarbul",
    "Call of the Ring",
    "Cavern-Hoard Dragon",
    "Choked Estuary",
    "Claim the Precious",
    "Commander's Sphere",
    "Corsairs of Umbar",
    "Crumbling Necropolis",
    "Desolate Lighthouse",
    "Dragonskull Summit",
    "Dreadhorde Invasion",
    "Drowned Catacomb",
    "Dunland Crebain",
    "Fall of Cair Andros",
    "Feed the Swarm",
    "Field of Ruin",
    "Fiery Inscription",
    "Foray of Orcs",
    "Foreboding Ruins",
    "Frostboil Snarl",
    "Glorious Gale",
    "Gollum, Patient Plotter",
    "Gothmog, Morgul Lieutenant",
    "Grishnákh, Brash Instigator",
    "Gríma, Saruman's Footman",
    "In the Darkness Bind Them",
    "Inherited Envelope",
    "Island",
    "Lazotep Plating",
    "Living Death",
    "Lord of the Nazgûl",
    "March from the Black Gate",
    "Mauhúr, Uruk-hai Captain",
    "Minas Morgul, Dark Fortress",
    "Mines of Moria",
    "Moria Scavenger",
    "Mount Doom",
    "Mountain",
    "Nazgûl",
    "Nazgûl Battle-Mace",
    "One Ring to Rule Them All",
    "Orcish Bowmasters",
    "Orcish Medicine",
    "Orcish Siegemaster",
    "Palantír of Orthanc",
    "Reanimate",
    "Relic of Sauron",
    "Ringsight",
    "Ringwraiths",
    "Rivendell",
    "Rogue's Passage",
    "Sam's Desperate Rescue",
    "Saruman the White",
    "Saruman's Trickery",
    "Saruman, the White Hand",
    "Sauron's Ransom",
    "Sauron, Lord of the Rings",
    "Sauron, the Necromancer",
    "Shadowspear",
    "Smoldering Marsh",
    "Soothing of Sméagol",
    "Sulfur Falls",
    "Sulfurous Springs",
    "Summons of Saruman",
    "Sunken Hollow",
    "Swamp",
    "The Balrog of Moria",
    "The Black Gate",
    "The Mouth of Sauron",
    "The One Ring",
    "The Ozolith",
    "Too Greedily, Too Deep",
    "Treason of Isengard",
    "Underground River",
    "Urborg, Tomb of Yawgmoth",
    "Warg Rider",
    "Widespread Brutality",
    "Witch-king of Angmar",
    "Wonder",
    "Worn Powerstone",
]

SYNERGY_PAIRS = []
SUPPLEMENT_FILTERS = []
